/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.enums;


import org.jooq.*;


// @formatter:off
/**
 * Optionally, other database items can be linked to this. As an example, an
 * overlay can be linked to a climate variable.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ViewTableMapoverlaysReferenceTable implements EnumType {

    phenotypes("phenotypes"),

    climates("climates");

    private final String literal;

    private ViewTableMapoverlaysReferenceTable(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static ViewTableMapoverlaysReferenceTable lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ViewTableMapoverlaysReferenceTable.class, literal);
    }
    // @formatter:on
}
