package jhi.germinate.server.database.pojo;

public enum ImportStatus
{
	GENERIC_DUPLICATE_COLUMN(true),
	GENERIC_IO_ERROR,
	GENERIC_MISSING_EXCEL_SHEET(true),
	GENERIC_MISSING_COLUMN(true),
	GENERIC_MISSING_COUNTRY,
	GENERIC_MISSING_REQUIRED_VALUE,
	GENERIC_MISSING_DB_ITEM_UPDATE,
	GENERIC_VALUE_TOO_LONG,
	GENERIC_INVALID_COUNTRY_CODE,
	GENERIC_INVALID_NUMBER,
	GENERIC_INVALID_BOOLEAN,
	GENERIC_INVALID_DATE,
	GENERIC_INVALID_DATATYPE,
	GENERIC_INVALID_MARKER,
	GENERIC_INVALID_LOCATION,
	GENERIC_INVALID_GERMPLASM,
	GENERIC_DUPLICATE_VALUE,
	GENERIC_INVALID_REFERENCE,
	GENERIC_DISPLAY_NAME_USED_BUT_NOT_UNIQUE,
	GROUP_INVALID_GROUP_VISIBILITY,
	GROUP_INVALID_CELL_VALUE,
	GROUP_HEADER_MISMATCH,
	MCPD_DUPLICATE_ACCENUMB,
	MCPD_MISSING_FIELD,
	MCPD_INVALID_SAMPSTAT,
	MCPD_INVALID_COLLSRC,
	MCPD_INVALID_DMS,
	MCPD_INVALID_MLSSTATUS,
	MCPD_INVALID_STORAGE,
	MCPD_INVALID_ENTITY_TYPE,
	MCPD_INVALID_ENTITY_PARENT_ACCENUMB,
	MCPD_MISSING_ACCENUMB,
	MCPD_INVALID_DUPLINST_NAME_MAPPING,
	TRIALS_INVALID_TRAIT_DATATYPE(true),
	TRIALS_INVALID_TRAIT_CATEGORIES(true),
	TRIALS_MISSING_TRAIT_DECLARATION(true),
	TRIALS_DATA_DATE_HEADER_MISMATCH,
	TRIALS_DATA_DATE_IDENTIFIER_MISMATCH,
	TRIALS_DATA_VIOLATES_RESTRICTION,
	TRIALS_ROW_COL_MISMATCH,
	TRIALS_DATA_REP_MISSING,
	COMPOUND_DATA_DATE_HEADER_MISMATCH,
	COMPOUND_DATA_DATE_IDENTIFIER_MISMATCH,
	COMPOUND_MISSING_COMPOUND_DECLARATION(true),
	CLIMATE_MISSING_CLIMATE_DECLARATION(true),
	CLIMATE_MISSING_LOCATION_DECLARATION,
	GENOTYPE_MISSING_ROW(true),
	GENOTYPE_HEADER_LENGTH_MISMATCH,
	GENOTYPE_HAPMAP_INCORRECT_HEADER,
	GENOTYPE_HAPMAP_INCORRECT_ROW_LENGTH,
	IMAGE_TEMPLATE_MISSING,
	IMAGE_IMAGE_MISSING,
	IMAGE_DEFINITION_MISSING,
	SHAPEFILE_MISSING_SHP,
	SHAPEFILE_MISSING_FIELD,
	SHAPEFILE_INVALID_ACCENUMB,
	SHAPEFILE_ROW_COL_GERMPLASM_CONFLICT,
	SHAPEFILE_DUPLICATE_ROW_COL,
	SHAPEFILE_WARNING_MISSING_ACCENUMB;

	private boolean allowsMultiple = false;

	private ImportStatus()
	{
	}

	private ImportStatus(boolean allowsMultiple)
	{
		this.allowsMultiple = allowsMultiple;
	}

	public boolean isAllowsMultiple()
	{
		return allowsMultiple;
	}
}
