/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collaborators implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    firstName;
    private String    lastName;
    private String    email;
    private String    phone;
    private String    externalId;
    private Integer   institutionId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Collaborators() {}

    public Collaborators(Collaborators value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.phone = value.phone;
        this.externalId = value.externalId;
        this.institutionId = value.institutionId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Collaborators(
        Integer   id,
        String    firstName,
        String    lastName,
        String    email,
        String    phone,
        String    externalId,
        Integer   institutionId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.externalId = externalId;
        this.institutionId = institutionId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>germinate_db.collaborators.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>germinate_db.collaborators.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>germinate_db.collaborators.first_name</code>. Last name
     * (surname) of the author(s), researcher(s), scientist(s), student(s)
     * responsible for producing the information product.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>germinate_db.collaborators.first_name</code>. Last name
     * (surname) of the author(s), researcher(s), scientist(s), student(s)
     * responsible for producing the information product.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>germinate_db.collaborators.last_name</code>. First name
     * (and middle name if available) of the author(s), researcher(s),
     * scientist(s), student(s) responsible for producing the information
     * product.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>germinate_db.collaborators.last_name</code>. First name
     * (and middle name if available) of the author(s), researcher(s),
     * scientist(s), student(s) responsible for producing the information
     * product.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>germinate_db.collaborators.email</code>. E-mail address
     * of the author(s), researcher(s), scientist(s), student(s) responsible for
     * producing the information product.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>germinate_db.collaborators.email</code>. E-mail address
     * of the author(s), researcher(s), scientist(s), student(s) responsible for
     * producing the information product.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>germinate_db.collaborators.phone</code>. Phone number of
     * the author(s), researcher(s), scientist(s), student(s) responsible for
     * producing the information product.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>germinate_db.collaborators.phone</code>. Phone number of
     * the author(s), researcher(s), scientist(s), student(s) responsible for
     * producing the information product.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>germinate_db.collaborators.external_id</code>. An
     * identifier for the data submitter. If that submitter is an individual,
     * ORCID identifiers are recommended.
     */
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Setter for <code>germinate_db.collaborators.external_id</code>. An
     * identifier for the data submitter. If that submitter is an individual,
     * ORCID identifiers are recommended.
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for <code>germinate_db.collaborators.institution_id</code>.
     * Author's affiliation when the resource was created. Foreign key to
     * 'institutions'
     */
    public Integer getInstitutionId() {
        return this.institutionId;
    }

    /**
     * Setter for <code>germinate_db.collaborators.institution_id</code>.
     * Author's affiliation when the resource was created. Foreign key to
     * 'institutions'
     */
    public void setInstitutionId(Integer institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * Getter for <code>germinate_db.collaborators.created_on</code>. When the
     * record was created.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>germinate_db.collaborators.created_on</code>. When the
     * record was created.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>germinate_db.collaborators.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>germinate_db.collaborators.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Collaborators (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(externalId);
        sb.append(", ").append(institutionId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
