/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * Defines the comment type.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commenttypes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    description;
    private String    referenceTable;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Commenttypes() {}

    public Commenttypes(Commenttypes value) {
        this.id = value.id;
        this.description = value.description;
        this.referenceTable = value.referenceTable;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Commenttypes(
        Integer   id,
        String    description,
        String    referenceTable,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.description = description;
        this.referenceTable = referenceTable;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Commenttypes (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(referenceTable);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
