/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import lombok.*;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.sql.Timestamp;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Datasetmembertypes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String targetTable;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Datasetmembertypes() {}

    public Datasetmembertypes(Datasetmembertypes value) {
        this.id = value.id;
        this.targetTable = value.targetTable;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Datasetmembertypes(
        Integer id,
        String targetTable,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.targetTable = targetTable;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Datasetmembertypes other = (Datasetmembertypes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.targetTable == null) {
            if (other.targetTable != null)
                return false;
        }
        else if (!this.targetTable.equals(other.targetTable))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.targetTable == null) ? 0 : this.targetTable.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Datasetmembertypes (");

        sb.append(id);
        sb.append(", ").append(targetTable);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
