/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fileresourcetypes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    name;
    private String    description;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Fileresourcetypes() {}

    public Fileresourcetypes(Fileresourcetypes value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Fileresourcetypes(
        Integer   id,
        String    name,
        String    description,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.id</code>. The primary
     * id.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.id</code>. The primary
     * id.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.name</code>. The name of
     * the file type.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.name</code>. The name of
     * the file type.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.description</code>. The
     * description of the file type.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.description</code>. The
     * description of the file type.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.created_on</code>. When
     * this record was created.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.created_on</code>. When
     * this record was created.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.updated_on</code>. When
     * this record was last updated.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.updated_on</code>. When
     * this record was last updated.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Fileresourcetypes (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
