/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import jhi.germinate.server.database.pojo.Exif;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Images implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   imagetypeId;
    private String    description;
    private Integer   foreignId;
    private String    path;
    private Exif      exif;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Images() {}

    public Images(Images value) {
        this.id = value.id;
        this.imagetypeId = value.imagetypeId;
        this.description = value.description;
        this.foreignId = value.foreignId;
        this.path = value.path;
        this.exif = value.exif;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Images(
        Integer   id,
        Integer   imagetypeId,
        String    description,
        Integer   foreignId,
        String    path,
        Exif      exif,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.imagetypeId = imagetypeId;
        this.description = description;
        this.foreignId = foreignId;
        this.path = path;
        this.exif = exif;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>germinate_db.images.id</code>. Primary id for this
     * table. This uniquely identifies the row.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>germinate_db.images.id</code>. Primary id for this
     * table. This uniquely identifies the row.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>germinate_db.images.imagetype_id</code>. Foreign key to
     * imagetypes (imagetypes.id).
     */
    public Integer getImagetypeId() {
        return this.imagetypeId;
    }

    /**
     * Setter for <code>germinate_db.images.imagetype_id</code>. Foreign key to
     * imagetypes (imagetypes.id).
     */
    public void setImagetypeId(Integer imagetypeId) {
        this.imagetypeId = imagetypeId;
    }

    /**
     * Getter for <code>germinate_db.images.description</code>. A description of
     * what the image shows if required.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>germinate_db.images.description</code>. A description of
     * what the image shows if required.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>germinate_db.images.foreign_id</code>. Relates to the
     * UID of the table to which the comment relates.
     */
    public Integer getForeignId() {
        return this.foreignId;
    }

    /**
     * Setter for <code>germinate_db.images.foreign_id</code>. Relates to the
     * UID of the table to which the comment relates.
     */
    public void setForeignId(Integer foreignId) {
        this.foreignId = foreignId;
    }

    /**
     * Getter for <code>germinate_db.images.path</code>. The file system path to
     * the image.
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>germinate_db.images.path</code>. The file system path to
     * the image.
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>germinate_db.images.exif</code>.
     */
    public Exif getExif() {
        return this.exif;
    }

    /**
     * Setter for <code>germinate_db.images.exif</code>.
     */
    public void setExif(Exif exif) {
        this.exif = exif;
    }

    /**
     * Getter for <code>germinate_db.images.created_on</code>. When the record
     * was created.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>germinate_db.images.created_on</code>. When the record
     * was created.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>germinate_db.images.updated_on</code>. When the record
     * was updated. This may be different from the created on date if subsequent
     * changes have been made to the underlying record.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>germinate_db.images.updated_on</code>. When the record
     * was updated. This may be different from the created on date if subsequent
     * changes have been made to the underlying record.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Images (");

        sb.append(id);
        sb.append(", ").append(imagetypeId);
        sb.append(", ").append(description);
        sb.append(", ").append(foreignId);
        sb.append(", ").append(path);
        sb.append(", ").append(exif);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
