/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * Describes the marker type. Markers (markers) have a defined type. This could
 * be AFLP, MicroSat, SNP and so on. Used to differentiate markers within the
 * markers table and alllows for mixing of marker types on genetic and physical
 * maps.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Markertypes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    description;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Markertypes() {}

    public Markertypes(Markertypes value) {
        this.id = value.id;
        this.description = value.description;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Markertypes(
        Integer   id,
        String    description,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.description = description;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Markertypes (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
