/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Publications implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    doi;
    private String    fallbackCache;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Publications() {}

    public Publications(Publications value) {
        this.id = value.id;
        this.doi = value.doi;
        this.fallbackCache = value.fallbackCache;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Publications(
        Integer   id,
        String    doi,
        String    fallbackCache,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.doi = doi;
        this.fallbackCache = fallbackCache;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Publications (");

        sb.append(id);
        sb.append(", ").append(doi);
        sb.append(", ").append(fallbackCache);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
