/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Traitontologies implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer ontologyId;
    private Integer traitId;
    private String ontologyPuid;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Traitontologies() {}

    public Traitontologies(Traitontologies value) {
        this.ontologyId = value.ontologyId;
        this.traitId = value.traitId;
        this.ontologyPuid = value.ontologyPuid;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Traitontologies(
        Integer ontologyId,
        Integer traitId,
        String ontologyPuid,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.ontologyId = ontologyId;
        this.traitId = traitId;
        this.ontologyPuid = ontologyPuid;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Traitontologies other = (Traitontologies) obj;
        if (this.ontologyId == null) {
            if (other.ontologyId != null)
                return false;
        }
        else if (!this.ontologyId.equals(other.ontologyId))
            return false;
        if (this.traitId == null) {
            if (other.traitId != null)
                return false;
        }
        else if (!this.traitId.equals(other.traitId))
            return false;
        if (this.ontologyPuid == null) {
            if (other.ontologyPuid != null)
                return false;
        }
        else if (!this.ontologyPuid.equals(other.ontologyPuid))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.ontologyId == null) ? 0 : this.ontologyId.hashCode());
        result = prime * result + ((this.traitId == null) ? 0 : this.traitId.hashCode());
        result = prime * result + ((this.ontologyPuid == null) ? 0 : this.ontologyPuid.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Traitontologies (");

        sb.append(ontologyId);
        sb.append(", ").append(traitId);
        sb.append(", ").append(ontologyPuid);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
