/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * The 'units' table holds descriptions of the various units that are used in
 * the Germinate database. Examples of these would include International System
 * of Units (SI) base units: kilogram, meter, second, ampere, kelvin, candela
 * and mole but can include any units that are required.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Units implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    unitName;
    private String    unitAbbreviation;
    private String    unitDescription;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Units() {}

    public Units(Units value) {
        this.id = value.id;
        this.unitName = value.unitName;
        this.unitAbbreviation = value.unitAbbreviation;
        this.unitDescription = value.unitDescription;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Units(
        Integer   id,
        String    unitName,
        String    unitAbbreviation,
        String    unitDescription,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.unitName = unitName;
        this.unitAbbreviation = unitAbbreviation;
        this.unitDescription = unitDescription;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Units (");

        sb.append(id);
        sb.append(", ").append(unitName);
        sb.append(", ").append(unitAbbreviation);
        sb.append(", ").append(unitDescription);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
