/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTablePedigreedefinitions implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   germplasmId;
    private String    germplasmName;
    private String    pedigreeNotationName;
    private String    pedigreeNotationDescription;
    private String    pedigreeNotationUrl;
    private Integer   datasetId;
    private String    datasetName;
    private Integer   definitionId;
    private String    definition;
    private String    pedigreeDescriptionName;
    private String    pedigreeDescriptionDescription;
    private String    pedigreeDescriptionAuthor;
    private Timestamp createdOn;

    public ViewTablePedigreedefinitions() {}

    public ViewTablePedigreedefinitions(ViewTablePedigreedefinitions value) {
        this.germplasmId = value.germplasmId;
        this.germplasmName = value.germplasmName;
        this.pedigreeNotationName = value.pedigreeNotationName;
        this.pedigreeNotationDescription = value.pedigreeNotationDescription;
        this.pedigreeNotationUrl = value.pedigreeNotationUrl;
        this.datasetId = value.datasetId;
        this.datasetName = value.datasetName;
        this.definitionId = value.definitionId;
        this.definition = value.definition;
        this.pedigreeDescriptionName = value.pedigreeDescriptionName;
        this.pedigreeDescriptionDescription = value.pedigreeDescriptionDescription;
        this.pedigreeDescriptionAuthor = value.pedigreeDescriptionAuthor;
        this.createdOn = value.createdOn;
    }

    public ViewTablePedigreedefinitions(
        Integer   germplasmId,
        String    germplasmName,
        String    pedigreeNotationName,
        String    pedigreeNotationDescription,
        String    pedigreeNotationUrl,
        Integer   datasetId,
        String    datasetName,
        Integer   definitionId,
        String    definition,
        String    pedigreeDescriptionName,
        String    pedigreeDescriptionDescription,
        String    pedigreeDescriptionAuthor,
        Timestamp createdOn
    ) {
        this.germplasmId = germplasmId;
        this.germplasmName = germplasmName;
        this.pedigreeNotationName = pedigreeNotationName;
        this.pedigreeNotationDescription = pedigreeNotationDescription;
        this.pedigreeNotationUrl = pedigreeNotationUrl;
        this.datasetId = datasetId;
        this.datasetName = datasetName;
        this.definitionId = definitionId;
        this.definition = definition;
        this.pedigreeDescriptionName = pedigreeDescriptionName;
        this.pedigreeDescriptionDescription = pedigreeDescriptionDescription;
        this.pedigreeDescriptionAuthor = pedigreeDescriptionAuthor;
        this.createdOn = createdOn;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getGermplasmId() {
        return this.germplasmId;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setGermplasmId(Integer germplasmId) {
        this.germplasmId = germplasmId;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_name</code>.
     * A unique name which defines an entry in the germinatbase table.
     */
    public String getGermplasmName() {
        return this.germplasmName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_name</code>.
     * A unique name which defines an entry in the germinatbase table.
     */
    public void setGermplasmName(String germplasmName) {
        this.germplasmName = germplasmName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_name</code>.
     * Name of the reference notation source.
     */
    public String getPedigreeNotationName() {
        return this.pedigreeNotationName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_name</code>.
     * Name of the reference notation source.
     */
    public void setPedigreeNotationName(String pedigreeNotationName) {
        this.pedigreeNotationName = pedigreeNotationName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_description</code>.
     * A longer description about the reference notation source.
     */
    public String getPedigreeNotationDescription() {
        return this.pedigreeNotationDescription;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_description</code>.
     * A longer description about the reference notation source.
     */
    public void setPedigreeNotationDescription(String pedigreeNotationDescription) {
        this.pedigreeNotationDescription = pedigreeNotationDescription;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_url</code>.
     * Hyperlink to the notation source.
     */
    public String getPedigreeNotationUrl() {
        return this.pedigreeNotationUrl;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_url</code>.
     * Hyperlink to the notation source.
     */
    public void setPedigreeNotationUrl(String pedigreeNotationUrl) {
        this.pedigreeNotationUrl = pedigreeNotationUrl;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setDatasetId(Integer datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_name</code>.
     * Describes the dataset.
     */
    public String getDatasetName() {
        return this.datasetName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_name</code>.
     * Describes the dataset.
     */
    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getDefinitionId() {
        return this.definitionId;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setDefinitionId(Integer definitionId) {
        this.definitionId = definitionId;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition</code>. The
     * pedigree string which is used to represent the germinatebase entry.
     */
    public String getDefinition() {
        return this.definition;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition</code>. The
     * pedigree string which is used to represent the germinatebase entry.
     */
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_name</code>.
     * The name of the pedigree.
     */
    public String getPedigreeDescriptionName() {
        return this.pedigreeDescriptionName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_name</code>.
     * The name of the pedigree.
     */
    public void setPedigreeDescriptionName(String pedigreeDescriptionName) {
        this.pedigreeDescriptionName = pedigreeDescriptionName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_description</code>.
     * Describes the pedigree in more detail.
     */
    public String getPedigreeDescriptionDescription() {
        return this.pedigreeDescriptionDescription;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_description</code>.
     * Describes the pedigree in more detail.
     */
    public void setPedigreeDescriptionDescription(String pedigreeDescriptionDescription) {
        this.pedigreeDescriptionDescription = pedigreeDescriptionDescription;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_author</code>.
     * Who is responsible for the creation of the pedigree. Attribution should
     * be included in here for pedigree sources.
     */
    public String getPedigreeDescriptionAuthor() {
        return this.pedigreeDescriptionAuthor;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_author</code>.
     * Who is responsible for the creation of the pedigree. Attribution should
     * be included in here for pedigree sources.
     */
    public void setPedigreeDescriptionAuthor(String pedigreeDescriptionAuthor) {
        this.pedigreeDescriptionAuthor = pedigreeDescriptionAuthor;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.created_on</code>. When
     * the record was created.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.created_on</code>. When
     * the record was created.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTablePedigreedefinitions (");

        sb.append(germplasmId);
        sb.append(", ").append(germplasmName);
        sb.append(", ").append(pedigreeNotationName);
        sb.append(", ").append(pedigreeNotationDescription);
        sb.append(", ").append(pedigreeNotationUrl);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(datasetName);
        sb.append(", ").append(definitionId);
        sb.append(", ").append(definition);
        sb.append(", ").append(pedigreeDescriptionName);
        sb.append(", ").append(pedigreeDescriptionDescription);
        sb.append(", ").append(pedigreeDescriptionAuthor);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
