/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;

import jhi.germinate.server.database.codegen.enums.ViewTableTraitsTemplateDataType;

import org.jooq.JSON;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTraitsTemplate implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private String shortName;
    private String description;
    private ViewTableTraitsTemplateDataType dataType;
    private String unitName;
    private String unitAbbreviation;
    private String unitDescriptions;
    private JSON traitCategories_28commaSeparated_29;
    private JSON min_28onlyForNumericTraits_29;
    private JSON max_28onlyForNumericTraits_29;
    private Long setSize;
    private String isTimeseries;
    private String traitCategory;

    public ViewTableTraitsTemplate() {}

    public ViewTableTraitsTemplate(ViewTableTraitsTemplate value) {
        this.name = value.name;
        this.shortName = value.shortName;
        this.description = value.description;
        this.dataType = value.dataType;
        this.unitName = value.unitName;
        this.unitAbbreviation = value.unitAbbreviation;
        this.unitDescriptions = value.unitDescriptions;
        this.traitCategories_28commaSeparated_29 = value.traitCategories_28commaSeparated_29;
        this.min_28onlyForNumericTraits_29 = value.min_28onlyForNumericTraits_29;
        this.max_28onlyForNumericTraits_29 = value.max_28onlyForNumericTraits_29;
        this.setSize = value.setSize;
        this.isTimeseries = value.isTimeseries;
        this.traitCategory = value.traitCategory;
    }

    public ViewTableTraitsTemplate(
        String name,
        String shortName,
        String description,
        ViewTableTraitsTemplateDataType dataType,
        String unitName,
        String unitAbbreviation,
        String unitDescriptions,
        JSON traitCategories_28commaSeparated_29,
        JSON min_28onlyForNumericTraits_29,
        JSON max_28onlyForNumericTraits_29,
        Long setSize,
        String isTimeseries,
        String traitCategory
    ) {
        this.name = name;
        this.shortName = shortName;
        this.description = description;
        this.dataType = dataType;
        this.unitName = unitName;
        this.unitAbbreviation = unitAbbreviation;
        this.unitDescriptions = unitDescriptions;
        this.traitCategories_28commaSeparated_29 = traitCategories_28commaSeparated_29;
        this.min_28onlyForNumericTraits_29 = min_28onlyForNumericTraits_29;
        this.max_28onlyForNumericTraits_29 = max_28onlyForNumericTraits_29;
        this.setSize = setSize;
        this.isTimeseries = isTimeseries;
        this.traitCategory = traitCategory;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ViewTableTraitsTemplate other = (ViewTableTraitsTemplate) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.shortName == null) {
            if (other.shortName != null)
                return false;
        }
        else if (!this.shortName.equals(other.shortName))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.dataType == null) {
            if (other.dataType != null)
                return false;
        }
        else if (!this.dataType.equals(other.dataType))
            return false;
        if (this.unitName == null) {
            if (other.unitName != null)
                return false;
        }
        else if (!this.unitName.equals(other.unitName))
            return false;
        if (this.unitAbbreviation == null) {
            if (other.unitAbbreviation != null)
                return false;
        }
        else if (!this.unitAbbreviation.equals(other.unitAbbreviation))
            return false;
        if (this.unitDescriptions == null) {
            if (other.unitDescriptions != null)
                return false;
        }
        else if (!this.unitDescriptions.equals(other.unitDescriptions))
            return false;
        if (this.traitCategories_28commaSeparated_29 == null) {
            if (other.traitCategories_28commaSeparated_29 != null)
                return false;
        }
        else if (!this.traitCategories_28commaSeparated_29.equals(other.traitCategories_28commaSeparated_29))
            return false;
        if (this.min_28onlyForNumericTraits_29 == null) {
            if (other.min_28onlyForNumericTraits_29 != null)
                return false;
        }
        else if (!this.min_28onlyForNumericTraits_29.equals(other.min_28onlyForNumericTraits_29))
            return false;
        if (this.max_28onlyForNumericTraits_29 == null) {
            if (other.max_28onlyForNumericTraits_29 != null)
                return false;
        }
        else if (!this.max_28onlyForNumericTraits_29.equals(other.max_28onlyForNumericTraits_29))
            return false;
        if (this.setSize == null) {
            if (other.setSize != null)
                return false;
        }
        else if (!this.setSize.equals(other.setSize))
            return false;
        if (this.isTimeseries == null) {
            if (other.isTimeseries != null)
                return false;
        }
        else if (!this.isTimeseries.equals(other.isTimeseries))
            return false;
        if (this.traitCategory == null) {
            if (other.traitCategory != null)
                return false;
        }
        else if (!this.traitCategory.equals(other.traitCategory))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.shortName == null) ? 0 : this.shortName.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.dataType == null) ? 0 : this.dataType.hashCode());
        result = prime * result + ((this.unitName == null) ? 0 : this.unitName.hashCode());
        result = prime * result + ((this.unitAbbreviation == null) ? 0 : this.unitAbbreviation.hashCode());
        result = prime * result + ((this.unitDescriptions == null) ? 0 : this.unitDescriptions.hashCode());
        result = prime * result + ((this.traitCategories_28commaSeparated_29 == null) ? 0 : this.traitCategories_28commaSeparated_29.hashCode());
        result = prime * result + ((this.min_28onlyForNumericTraits_29 == null) ? 0 : this.min_28onlyForNumericTraits_29.hashCode());
        result = prime * result + ((this.max_28onlyForNumericTraits_29 == null) ? 0 : this.max_28onlyForNumericTraits_29.hashCode());
        result = prime * result + ((this.setSize == null) ? 0 : this.setSize.hashCode());
        result = prime * result + ((this.isTimeseries == null) ? 0 : this.isTimeseries.hashCode());
        result = prime * result + ((this.traitCategory == null) ? 0 : this.traitCategory.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableTraitsTemplate (");

        sb.append(name);
        sb.append(", ").append(shortName);
        sb.append(", ").append(description);
        sb.append(", ").append(dataType);
        sb.append(", ").append(unitName);
        sb.append(", ").append(unitAbbreviation);
        sb.append(", ").append(unitDescriptions);
        sb.append(", ").append(traitCategories_28commaSeparated_29);
        sb.append(", ").append(min_28onlyForNumericTraits_29);
        sb.append(", ").append(max_28onlyForNumericTraits_29);
        sb.append(", ").append(setSize);
        sb.append(", ").append(isTimeseries);
        sb.append(", ").append(traitCategory);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
