/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableClimateData implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer    locationId;
    private String     locationName;
    private String     locationRegion;
    private String     locationState;
    private String     locationType;
    private BigDecimal locationLatitude;
    private BigDecimal locationLongitude;
    private BigDecimal locationElevation;
    private String     countryName;
    private String     countryCode2;
    private String     countryCode3;
    private Integer    datasetId;
    private String     datasetName;
    private String     datasetDescription;
    private Integer    climateId;
    private String     climateName;
    private String     climateNameShort;
    private String     unitName;
    private Timestamp  recordingDate;
    private Double     climateValue;

    public ViewTableClimateData() {}

    public ViewTableClimateData(ViewTableClimateData value) {
        this.locationId = value.locationId;
        this.locationName = value.locationName;
        this.locationRegion = value.locationRegion;
        this.locationState = value.locationState;
        this.locationType = value.locationType;
        this.locationLatitude = value.locationLatitude;
        this.locationLongitude = value.locationLongitude;
        this.locationElevation = value.locationElevation;
        this.countryName = value.countryName;
        this.countryCode2 = value.countryCode2;
        this.countryCode3 = value.countryCode3;
        this.datasetId = value.datasetId;
        this.datasetName = value.datasetName;
        this.datasetDescription = value.datasetDescription;
        this.climateId = value.climateId;
        this.climateName = value.climateName;
        this.climateNameShort = value.climateNameShort;
        this.unitName = value.unitName;
        this.recordingDate = value.recordingDate;
        this.climateValue = value.climateValue;
    }

    public ViewTableClimateData(
        Integer    locationId,
        String     locationName,
        String     locationRegion,
        String     locationState,
        String     locationType,
        BigDecimal locationLatitude,
        BigDecimal locationLongitude,
        BigDecimal locationElevation,
        String     countryName,
        String     countryCode2,
        String     countryCode3,
        Integer    datasetId,
        String     datasetName,
        String     datasetDescription,
        Integer    climateId,
        String     climateName,
        String     climateNameShort,
        String     unitName,
        Timestamp  recordingDate,
        Double     climateValue
    ) {
        this.locationId = locationId;
        this.locationName = locationName;
        this.locationRegion = locationRegion;
        this.locationState = locationState;
        this.locationType = locationType;
        this.locationLatitude = locationLatitude;
        this.locationLongitude = locationLongitude;
        this.locationElevation = locationElevation;
        this.countryName = countryName;
        this.countryCode2 = countryCode2;
        this.countryCode3 = countryCode3;
        this.datasetId = datasetId;
        this.datasetName = datasetName;
        this.datasetDescription = datasetDescription;
        this.climateId = climateId;
        this.climateName = climateName;
        this.climateNameShort = climateNameShort;
        this.unitName = unitName;
        this.recordingDate = recordingDate;
        this.climateValue = climateValue;
    }

    /**
     * Getter for <code>germinate_db.view_table_climate_data.location_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getLocationId() {
        return this.locationId;
    }

    /**
     * Setter for <code>germinate_db.view_table_climate_data.location_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_name</code>. The site
     * name where the location is.
     */
    public String getLocationName() {
        return this.locationName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_name</code>. The site
     * name where the location is.
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_region</code>. The
     * region where the location is if this exists.
     */
    public String getLocationRegion() {
        return this.locationRegion;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_region</code>. The
     * region where the location is if this exists.
     */
    public void setLocationRegion(String locationRegion) {
        this.locationRegion = locationRegion;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_state</code>. The
     * state where the location is if this exists.
     */
    public String getLocationState() {
        return this.locationState;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_state</code>. The
     * state where the location is if this exists.
     */
    public void setLocationState(String locationState) {
        this.locationState = locationState;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_type</code>. The name
     * of the location type. 
     */
    public String getLocationType() {
        return this.locationType;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_type</code>. The name
     * of the location type. 
     */
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_latitude</code>.
     * Latitude of the location.
     */
    public BigDecimal getLocationLatitude() {
        return this.locationLatitude;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_latitude</code>.
     * Latitude of the location.
     */
    public void setLocationLatitude(BigDecimal locationLatitude) {
        this.locationLatitude = locationLatitude;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_longitude</code>.
     * Longitude of the location.
     */
    public BigDecimal getLocationLongitude() {
        return this.locationLongitude;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_longitude</code>.
     * Longitude of the location.
     */
    public void setLocationLongitude(BigDecimal locationLongitude) {
        this.locationLongitude = locationLongitude;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.location_elevation</code>. The
     * elevation of the site in metres.
     */
    public BigDecimal getLocationElevation() {
        return this.locationElevation;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.location_elevation</code>. The
     * elevation of the site in metres.
     */
    public void setLocationElevation(BigDecimal locationElevation) {
        this.locationElevation = locationElevation;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.country_name</code>. Country
     * name.
     */
    public String getCountryName() {
        return this.countryName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.country_name</code>. Country
     * name.
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.country_code2</code>. ISO 2
     * Code for country.
     */
    public String getCountryCode2() {
        return this.countryCode2;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.country_code2</code>. ISO 2
     * Code for country.
     */
    public void setCountryCode2(String countryCode2) {
        this.countryCode2 = countryCode2;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.country_code3</code>. ISO 3
     * Code for country.
     */
    public String getCountryCode3() {
        return this.countryCode3;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.country_code3</code>. ISO 3
     * Code for country.
     */
    public void setCountryCode3(String countryCode3) {
        this.countryCode3 = countryCode3;
    }

    /**
     * Getter for <code>germinate_db.view_table_climate_data.dataset_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>germinate_db.view_table_climate_data.dataset_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setDatasetId(Integer datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.dataset_name</code>. Describes
     * the dataset.
     */
    public String getDatasetName() {
        return this.datasetName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.dataset_name</code>. Describes
     * the dataset.
     */
    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.dataset_description</code>.
     * The name of this dataset.
     */
    public String getDatasetDescription() {
        return this.datasetDescription;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.dataset_description</code>.
     * The name of this dataset.
     */
    public void setDatasetDescription(String datasetDescription) {
        this.datasetDescription = datasetDescription;
    }

    /**
     * Getter for <code>germinate_db.view_table_climate_data.climate_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getClimateId() {
        return this.climateId;
    }

    /**
     * Setter for <code>germinate_db.view_table_climate_data.climate_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setClimateId(Integer climateId) {
        this.climateId = climateId;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.climate_name</code>. Describes
     * the climate.
     */
    public String getClimateName() {
        return this.climateName;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.climate_name</code>. Describes
     * the climate.
     */
    public void setClimateName(String climateName) {
        this.climateName = climateName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.climate_name_short</code>.
     * Shortened version of the climate name which is used in some table
     * headers.
     */
    public String getClimateNameShort() {
        return this.climateNameShort;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.climate_name_short</code>.
     * Shortened version of the climate name which is used in some table
     * headers.
     */
    public void setClimateNameShort(String climateNameShort) {
        this.climateNameShort = climateNameShort;
    }

    /**
     * Getter for <code>germinate_db.view_table_climate_data.unit_name</code>.
     * The name of the unit. This should be the name of the unit in full.
     */
    public String getUnitName() {
        return this.unitName;
    }

    /**
     * Setter for <code>germinate_db.view_table_climate_data.unit_name</code>.
     * The name of the unit. This should be the name of the unit in full.
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.recording_date</code>. The
     * date at which this data point was recorded.
     */
    public Timestamp getRecordingDate() {
        return this.recordingDate;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.recording_date</code>. The
     * date at which this data point was recorded.
     */
    public void setRecordingDate(Timestamp recordingDate) {
        this.recordingDate = recordingDate;
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_climate_data.climate_value</code>. Value
     * for the specific climate attribute. These are monthly averages and not
     * daily. Monthly data is required for the current Germinate climate
     * viisualizations and interface.
     */
    public Double getClimateValue() {
        return this.climateValue;
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_climate_data.climate_value</code>. Value
     * for the specific climate attribute. These are monthly averages and not
     * daily. Monthly data is required for the current Germinate climate
     * viisualizations and interface.
     */
    public void setClimateValue(Double climateValue) {
        this.climateValue = climateValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableClimateData (");

        sb.append(locationId);
        sb.append(", ").append(locationName);
        sb.append(", ").append(locationRegion);
        sb.append(", ").append(locationState);
        sb.append(", ").append(locationType);
        sb.append(", ").append(locationLatitude);
        sb.append(", ").append(locationLongitude);
        sb.append(", ").append(locationElevation);
        sb.append(", ").append(countryName);
        sb.append(", ").append(countryCode2);
        sb.append(", ").append(countryCode3);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(datasetName);
        sb.append(", ").append(datasetDescription);
        sb.append(", ").append(climateId);
        sb.append(", ").append(climateName);
        sb.append(", ").append(climateNameShort);
        sb.append(", ").append(unitName);
        sb.append(", ").append(recordingDate);
        sb.append(", ").append(climateValue);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
