/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import jhi.germinate.server.database.pojo.TaxonomyProviderInfo;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTaxonomies implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer taxonomyId;
    private String taxonomyGenus;
    private String taxonomySpecies;
    private String taxonomySubtaxa;
    private String taxonomyCropname;
    private TaxonomyProviderInfo[] taxonomyProviders;
    private Long count;

    public ViewTableTaxonomies() {}

    public ViewTableTaxonomies(ViewTableTaxonomies value) {
        this.taxonomyId = value.taxonomyId;
        this.taxonomyGenus = value.taxonomyGenus;
        this.taxonomySpecies = value.taxonomySpecies;
        this.taxonomySubtaxa = value.taxonomySubtaxa;
        this.taxonomyCropname = value.taxonomyCropname;
        this.taxonomyProviders = value.taxonomyProviders;
        this.count = value.count;
    }

    public ViewTableTaxonomies(
        Integer taxonomyId,
        String taxonomyGenus,
        String taxonomySpecies,
        String taxonomySubtaxa,
        String taxonomyCropname,
        TaxonomyProviderInfo[] taxonomyProviders,
        Long count
    ) {
        this.taxonomyId = taxonomyId;
        this.taxonomyGenus = taxonomyGenus;
        this.taxonomySpecies = taxonomySpecies;
        this.taxonomySubtaxa = taxonomySubtaxa;
        this.taxonomyCropname = taxonomyCropname;
        this.taxonomyProviders = taxonomyProviders;
        this.count = count;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ViewTableTaxonomies other = (ViewTableTaxonomies) obj;
        if (this.taxonomyId == null) {
            if (other.taxonomyId != null)
                return false;
        }
        else if (!this.taxonomyId.equals(other.taxonomyId))
            return false;
        if (this.taxonomyGenus == null) {
            if (other.taxonomyGenus != null)
                return false;
        }
        else if (!this.taxonomyGenus.equals(other.taxonomyGenus))
            return false;
        if (this.taxonomySpecies == null) {
            if (other.taxonomySpecies != null)
                return false;
        }
        else if (!this.taxonomySpecies.equals(other.taxonomySpecies))
            return false;
        if (this.taxonomySubtaxa == null) {
            if (other.taxonomySubtaxa != null)
                return false;
        }
        else if (!this.taxonomySubtaxa.equals(other.taxonomySubtaxa))
            return false;
        if (this.taxonomyCropname == null) {
            if (other.taxonomyCropname != null)
                return false;
        }
        else if (!this.taxonomyCropname.equals(other.taxonomyCropname))
            return false;
        if (this.taxonomyProviders == null) {
            if (other.taxonomyProviders != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.taxonomyProviders, other.taxonomyProviders))
            return false;
        if (this.count == null) {
            if (other.count != null)
                return false;
        }
        else if (!this.count.equals(other.count))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.taxonomyId == null) ? 0 : this.taxonomyId.hashCode());
        result = prime * result + ((this.taxonomyGenus == null) ? 0 : this.taxonomyGenus.hashCode());
        result = prime * result + ((this.taxonomySpecies == null) ? 0 : this.taxonomySpecies.hashCode());
        result = prime * result + ((this.taxonomySubtaxa == null) ? 0 : this.taxonomySubtaxa.hashCode());
        result = prime * result + ((this.taxonomyCropname == null) ? 0 : this.taxonomyCropname.hashCode());
        result = prime * result + ((this.taxonomyProviders == null) ? 0 : Arrays.deepHashCode(this.taxonomyProviders));
        result = prime * result + ((this.count == null) ? 0 : this.count.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableTaxonomies (");

        sb.append(taxonomyId);
        sb.append(", ").append(taxonomyGenus);
        sb.append(", ").append(taxonomySpecies);
        sb.append(", ").append(taxonomySubtaxa);
        sb.append(", ").append(taxonomyCropname);
        sb.append(", ").append(Arrays.deepToString(taxonomyProviders));
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
