/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;

import jhi.germinate.server.database.codegen.enums.ViewTableDatasetAttributesAttributeType;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableDatasetAttributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer                                 datasetId;
    private String                                  datasetName;
    private String                                  datasetDescription;
    private Integer                                 attributeId;
    private String                                  attributeName;
    private String                                  attributeDescription;
    private ViewTableDatasetAttributesAttributeType attributeType;
    private String                                  targetTable;
    private Integer                                 foreignId;
    private String                                  attributeValue;

    public ViewTableDatasetAttributes() {}

    public ViewTableDatasetAttributes(ViewTableDatasetAttributes value) {
        this.datasetId = value.datasetId;
        this.datasetName = value.datasetName;
        this.datasetDescription = value.datasetDescription;
        this.attributeId = value.attributeId;
        this.attributeName = value.attributeName;
        this.attributeDescription = value.attributeDescription;
        this.attributeType = value.attributeType;
        this.targetTable = value.targetTable;
        this.foreignId = value.foreignId;
        this.attributeValue = value.attributeValue;
    }

    public ViewTableDatasetAttributes(
        Integer                                 datasetId,
        String                                  datasetName,
        String                                  datasetDescription,
        Integer                                 attributeId,
        String                                  attributeName,
        String                                  attributeDescription,
        ViewTableDatasetAttributesAttributeType attributeType,
        String                                  targetTable,
        Integer                                 foreignId,
        String                                  attributeValue
    ) {
        this.datasetId = datasetId;
        this.datasetName = datasetName;
        this.datasetDescription = datasetDescription;
        this.attributeId = attributeId;
        this.attributeName = attributeName;
        this.attributeDescription = attributeDescription;
        this.attributeType = attributeType;
        this.targetTable = targetTable;
        this.foreignId = foreignId;
        this.attributeValue = attributeValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableDatasetAttributes (");

        sb.append(datasetId);
        sb.append(", ").append(datasetName);
        sb.append(", ").append(datasetDescription);
        sb.append(", ").append(attributeId);
        sb.append(", ").append(attributeName);
        sb.append(", ").append(attributeDescription);
        sb.append(", ").append(attributeType);
        sb.append(", ").append(targetTable);
        sb.append(", ").append(foreignId);
        sb.append(", ").append(attributeValue);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
