/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.enums.ViewTableGermplasmAttributesAttributeType;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableGermplasmAttributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer                                   attributeValueId;
    private Integer                                   germplasmId;
    private String                                    germplasmGid;
    private String                                    germplasmName;
    private Integer                                   attributeId;
    private String                                    attributeName;
    private String                                    attributeDescription;
    private ViewTableGermplasmAttributesAttributeType attributeType;
    private String                                    targetTable;
    private Integer                                   foreignId;
    private Timestamp                                 createdOn;
    private String                                    attributeValue;

    public ViewTableGermplasmAttributes() {}

    public ViewTableGermplasmAttributes(ViewTableGermplasmAttributes value) {
        this.attributeValueId = value.attributeValueId;
        this.germplasmId = value.germplasmId;
        this.germplasmGid = value.germplasmGid;
        this.germplasmName = value.germplasmName;
        this.attributeId = value.attributeId;
        this.attributeName = value.attributeName;
        this.attributeDescription = value.attributeDescription;
        this.attributeType = value.attributeType;
        this.targetTable = value.targetTable;
        this.foreignId = value.foreignId;
        this.createdOn = value.createdOn;
        this.attributeValue = value.attributeValue;
    }

    public ViewTableGermplasmAttributes(
        Integer                                   attributeValueId,
        Integer                                   germplasmId,
        String                                    germplasmGid,
        String                                    germplasmName,
        Integer                                   attributeId,
        String                                    attributeName,
        String                                    attributeDescription,
        ViewTableGermplasmAttributesAttributeType attributeType,
        String                                    targetTable,
        Integer                                   foreignId,
        Timestamp                                 createdOn,
        String                                    attributeValue
    ) {
        this.attributeValueId = attributeValueId;
        this.germplasmId = germplasmId;
        this.germplasmGid = germplasmGid;
        this.germplasmName = germplasmName;
        this.attributeId = attributeId;
        this.attributeName = attributeName;
        this.attributeDescription = attributeDescription;
        this.attributeType = attributeType;
        this.targetTable = targetTable;
        this.foreignId = foreignId;
        this.createdOn = createdOn;
        this.attributeValue = attributeValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableGermplasmAttributes (");

        sb.append(attributeValueId);
        sb.append(", ").append(germplasmId);
        sb.append(", ").append(germplasmGid);
        sb.append(", ").append(germplasmName);
        sb.append(", ").append(attributeId);
        sb.append(", ").append(attributeName);
        sb.append(", ").append(attributeDescription);
        sb.append(", ").append(attributeType);
        sb.append(", ").append(targetTable);
        sb.append(", ").append(foreignId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(attributeValue);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
