/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewStatsTaxonomy implements Serializable {

    private static final long serialVersionUID = 1L;

    private String genus;
    private String species;
    private String subtaxa;
    private Long   count;

    public ViewStatsTaxonomy() {}

    public ViewStatsTaxonomy(ViewStatsTaxonomy value) {
        this.genus = value.genus;
        this.species = value.species;
        this.subtaxa = value.subtaxa;
        this.count = value.count;
    }

    public ViewStatsTaxonomy(
        String genus,
        String species,
        String subtaxa,
        Long   count
    ) {
        this.genus = genus;
        this.species = species;
        this.subtaxa = subtaxa;
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewStatsTaxonomy (");

        sb.append(genus);
        sb.append(", ").append(species);
        sb.append(", ").append(subtaxa);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
