/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableMarkers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   markerId;
    private String    markerName;
    private String    markerType;
    private String[]  markerSynonyms;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ViewTableMarkers() {}

    public ViewTableMarkers(ViewTableMarkers value) {
        this.markerId = value.markerId;
        this.markerName = value.markerName;
        this.markerType = value.markerType;
        this.markerSynonyms = value.markerSynonyms;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ViewTableMarkers(
        Integer   markerId,
        String    markerName,
        String    markerType,
        String[]  markerSynonyms,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.markerId = markerId;
        this.markerName = markerName;
        this.markerType = markerType;
        this.markerSynonyms = markerSynonyms;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableMarkers (");

        sb.append(markerId);
        sb.append(", ").append(markerName);
        sb.append(", ").append(markerType);
        sb.append(", ").append(Arrays.toString(markerSynonyms));
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
