/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import jhi.germinate.server.database.codegen.enums.*;
import jhi.germinate.server.database.codegen.tables.DataImportJobs;
import jhi.germinate.server.database.pojo.*;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DataImportJobsRecord extends UpdatableRecordImpl<DataImportJobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.data_import_jobs.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.job_id</code>.
     */
    public void setJobId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.job_id</code>.
     */
    public String getJobId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.job_config</code>.
     */
    public void setJobConfig(ImportJobDetails value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.job_config</code>.
     */
    public ImportJobDetails getJobConfig() {
        return (ImportJobDetails) get(3);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.original_filename</code>.
     */
    public void setOriginalFilename(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.original_filename</code>.
     */
    public String getOriginalFilename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.is_update</code>.
     */
    public void setIsUpdate(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.is_update</code>.
     */
    public Boolean getIsUpdate() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.datasetstate_id</code>.
     */
    public void setDatasetstateId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.datasetstate_id</code>.
     */
    public Integer getDatasetstateId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.datatype</code>.
     */
    public void setDatatype(DataImportJobsDatatype value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.datatype</code>.
     */
    public DataImportJobsDatatype getDatatype() {
        return (DataImportJobsDatatype) get(8);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.status</code>.
     */
    public void setStatus(DataImportJobsStatus value) {
        set(9, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.status</code>.
     */
    public DataImportJobsStatus getStatus() {
        return (DataImportJobsStatus) get(9);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.imported</code>.
     */
    public void setImported(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.imported</code>.
     */
    public Boolean getImported() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.visibility</code>.
     */
    public void setVisibility(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.visibility</code>.
     */
    public Boolean getVisibility() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.feedback</code>.
     */
    public void setFeedback(ImportResult[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.feedback</code>.
     */
    public ImportResult[] getFeedback() {
        return (ImportResult[]) get(12);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.stats</code>.
     */
    public void setStats(ImportJobStats value) {
        set(13, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.stats</code>.
     */
    public ImportJobStats getStats() {
        return (ImportJobStats) get(13);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>germinate_db.data_import_jobs.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>germinate_db.data_import_jobs.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataImportJobsRecord
     */
    public DataImportJobsRecord() {
        super(DataImportJobs.DATA_IMPORT_JOBS);
    }

    /**
     * Create a detached, initialised DataImportJobsRecord
     */
    public DataImportJobsRecord(Integer id, String uuid, String jobId, ImportJobDetails jobConfig, Integer userId, String originalFilename, Boolean isUpdate, Integer datasetstateId, DataImportJobsDatatype datatype, DataImportJobsStatus status, Boolean imported, Boolean visibility, ImportResult[] feedback, ImportJobStats stats, Timestamp createdOn, Timestamp updatedOn) {
        super(DataImportJobs.DATA_IMPORT_JOBS);

        setId(id);
        setUuid(uuid);
        setJobId(jobId);
        setJobConfig(jobConfig);
        setUserId(userId);
        setOriginalFilename(originalFilename);
        setIsUpdate(isUpdate);
        setDatasetstateId(datasetstateId);
        setDatatype(datatype);
        setStatus(status);
        setImported(imported);
        setVisibility(visibility);
        setFeedback(feedback);
        setStats(stats);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised DataImportJobsRecord
     */
    public DataImportJobsRecord(jhi.germinate.server.database.codegen.tables.pojos.DataImportJobs value) {
        super(DataImportJobs.DATA_IMPORT_JOBS);

        if (value != null) {
            setId(value.getId());
            setUuid(value.getUuid());
            setJobId(value.getJobId());
            setJobConfig(value.getJobConfig());
            setUserId(value.getUserId());
            setOriginalFilename(value.getOriginalFilename());
            setIsUpdate(value.getIsUpdate());
            setDatasetstateId(value.getDatasetstateId());
            setDatatype(value.getDatatype());
            setStatus(value.getStatus());
            setImported(value.getImported());
            setVisibility(value.getVisibility());
            setFeedback(value.getFeedback());
            setStats(value.getStats());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
