/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import jhi.germinate.server.database.codegen.tables.Fileresourcetypes;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileresourcetypesRecord extends UpdatableRecordImpl<FileresourcetypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.fileresourcetypes.id</code>. The primary
     * id.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.id</code>. The primary
     * id.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.name</code>. The name of
     * the file type.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.name</code>. The name of
     * the file type.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.description</code>. The
     * description of the file type.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.description</code>. The
     * description of the file type.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.created_on</code>. When
     * this record was created.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.created_on</code>. When
     * this record was created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>germinate_db.fileresourcetypes.updated_on</code>. When
     * this record was last updated.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.fileresourcetypes.updated_on</code>. When
     * this record was last updated.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileresourcetypesRecord
     */
    public FileresourcetypesRecord() {
        super(Fileresourcetypes.FILERESOURCETYPES);
    }

    /**
     * Create a detached, initialised FileresourcetypesRecord
     */
    public FileresourcetypesRecord(Integer id, String name, String description, Timestamp createdOn, Timestamp updatedOn) {
        super(Fileresourcetypes.FILERESOURCETYPES);

        setId(id);
        setName(name);
        setDescription(description);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FileresourcetypesRecord
     */
    public FileresourcetypesRecord(jhi.germinate.server.database.codegen.tables.pojos.Fileresourcetypes value) {
        super(Fileresourcetypes.FILERESOURCETYPES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
