/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.tables.Phenotypedata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * Contains phenotypic data which has been collected.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhenotypedataRecord extends UpdatableRecordImpl<PhenotypedataRecord> implements Record16<Integer, Integer, Integer, String, String, BigDecimal, BigDecimal, BigDecimal, String, Integer, Timestamp, Timestamp, Timestamp, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.phenotypedata.id</code>. Primary id for
     * this table. This uniquely identifies the row.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.id</code>. Primary id for
     * this table. This uniquely identifies the row.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.phenotype_id</code>. Foreign
     * key phenotypes (phenotype.id).
     */
    public void setPhenotypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.phenotype_id</code>. Foreign
     * key phenotypes (phenotype.id).
     */
    public Integer getPhenotypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.germinatebase_id</code>.
     * Foreign key germinatebase (germinatebase.id).
     */
    public void setGerminatebaseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.germinatebase_id</code>.
     * Foreign key germinatebase (germinatebase.id).
     */
    public Integer getGerminatebaseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.rep</code>.
     */
    public void setRep(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.rep</code>.
     */
    public String getRep() {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.block</code>.
     */
    public void setBlock(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.block</code>.
     */
    public String getBlock() {
        return (String) get(4);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.elevation</code>.
     */
    public void setElevation(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.elevation</code>.
     */
    public BigDecimal getElevation() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.phenotype_value</code>. The
     * phenotype value for this phenotype_id and germinatebase_id combination.
     */
    public void setPhenotypeValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.phenotype_value</code>. The
     * phenotype value for this phenotype_id and germinatebase_id combination.
     */
    public String getPhenotypeValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.dataset_id</code>. Foreign
     * key datasets (datasets.id).
     */
    public void setDatasetId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.dataset_id</code>. Foreign
     * key datasets (datasets.id).
     */
    public Integer getDatasetId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.recording_date</code>. Date
     * when the phenotypic result was recorded. Should be formatted 'YYYY-MM-DD
     * HH:MM:SS' or just 'YYYY-MM-DD' where a timestamp is not available.
     */
    public void setRecordingDate(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.recording_date</code>. Date
     * when the phenotypic result was recorded. Should be formatted 'YYYY-MM-DD
     * HH:MM:SS' or just 'YYYY-MM-DD' where a timestamp is not available.
     */
    public Timestamp getRecordingDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.created_on</code>. When the
     * record was created.
     */
    public void setCreatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.created_on</code>. When the
     * record was created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public void setUpdatedOn(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.location_id</code>. Foreign
     * key to locations (locations.id).
     */
    public void setLocationId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.location_id</code>. Foreign
     * key to locations (locations.id).
     */
    public Integer getLocationId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.treatment_id</code>. Foreign
     * key to treatments (treatments.id).
     */
    public void setTreatmentId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.treatment_id</code>. Foreign
     * key to treatments (treatments.id).
     */
    public Integer getTreatmentId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>germinate_db.phenotypedata.trialseries_id</code>.
     * Foreign key to trialseries (trialseries.id).
     */
    public void setTrialseriesId(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>germinate_db.phenotypedata.trialseries_id</code>.
     * Foreign key to trialseries (trialseries.id).
     */
    public Integer getTrialseriesId() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, Integer, Integer, String, String, BigDecimal, BigDecimal, BigDecimal, String, Integer, Timestamp, Timestamp, Timestamp, Integer, Integer, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, Integer, Integer, String, String, BigDecimal, BigDecimal, BigDecimal, String, Integer, Timestamp, Timestamp, Timestamp, Integer, Integer, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Phenotypedata.PHENOTYPEDATA.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Phenotypedata.PHENOTYPEDATA.PHENOTYPE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Phenotypedata.PHENOTYPEDATA.GERMINATEBASE_ID;
    }

    @Override
    public Field<String> field4() {
        return Phenotypedata.PHENOTYPEDATA.REP;
    }

    @Override
    public Field<String> field5() {
        return Phenotypedata.PHENOTYPEDATA.BLOCK;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Phenotypedata.PHENOTYPEDATA.LATITUDE;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Phenotypedata.PHENOTYPEDATA.LONGITUDE;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Phenotypedata.PHENOTYPEDATA.ELEVATION;
    }

    @Override
    public Field<String> field9() {
        return Phenotypedata.PHENOTYPEDATA.PHENOTYPE_VALUE;
    }

    @Override
    public Field<Integer> field10() {
        return Phenotypedata.PHENOTYPEDATA.DATASET_ID;
    }

    @Override
    public Field<Timestamp> field11() {
        return Phenotypedata.PHENOTYPEDATA.RECORDING_DATE;
    }

    @Override
    public Field<Timestamp> field12() {
        return Phenotypedata.PHENOTYPEDATA.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field13() {
        return Phenotypedata.PHENOTYPEDATA.UPDATED_ON;
    }

    @Override
    public Field<Integer> field14() {
        return Phenotypedata.PHENOTYPEDATA.LOCATION_ID;
    }

    @Override
    public Field<Integer> field15() {
        return Phenotypedata.PHENOTYPEDATA.TREATMENT_ID;
    }

    @Override
    public Field<Integer> field16() {
        return Phenotypedata.PHENOTYPEDATA.TRIALSERIES_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPhenotypeId();
    }

    @Override
    public Integer component3() {
        return getGerminatebaseId();
    }

    @Override
    public String component4() {
        return getRep();
    }

    @Override
    public String component5() {
        return getBlock();
    }

    @Override
    public BigDecimal component6() {
        return getLatitude();
    }

    @Override
    public BigDecimal component7() {
        return getLongitude();
    }

    @Override
    public BigDecimal component8() {
        return getElevation();
    }

    @Override
    public String component9() {
        return getPhenotypeValue();
    }

    @Override
    public Integer component10() {
        return getDatasetId();
    }

    @Override
    public Timestamp component11() {
        return getRecordingDate();
    }

    @Override
    public Timestamp component12() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component13() {
        return getUpdatedOn();
    }

    @Override
    public Integer component14() {
        return getLocationId();
    }

    @Override
    public Integer component15() {
        return getTreatmentId();
    }

    @Override
    public Integer component16() {
        return getTrialseriesId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPhenotypeId();
    }

    @Override
    public Integer value3() {
        return getGerminatebaseId();
    }

    @Override
    public String value4() {
        return getRep();
    }

    @Override
    public String value5() {
        return getBlock();
    }

    @Override
    public BigDecimal value6() {
        return getLatitude();
    }

    @Override
    public BigDecimal value7() {
        return getLongitude();
    }

    @Override
    public BigDecimal value8() {
        return getElevation();
    }

    @Override
    public String value9() {
        return getPhenotypeValue();
    }

    @Override
    public Integer value10() {
        return getDatasetId();
    }

    @Override
    public Timestamp value11() {
        return getRecordingDate();
    }

    @Override
    public Timestamp value12() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value13() {
        return getUpdatedOn();
    }

    @Override
    public Integer value14() {
        return getLocationId();
    }

    @Override
    public Integer value15() {
        return getTreatmentId();
    }

    @Override
    public Integer value16() {
        return getTrialseriesId();
    }

    @Override
    public PhenotypedataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value2(Integer value) {
        setPhenotypeId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value3(Integer value) {
        setGerminatebaseId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value4(String value) {
        setRep(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value5(String value) {
        setBlock(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value6(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value7(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value8(BigDecimal value) {
        setElevation(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value9(String value) {
        setPhenotypeValue(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value10(Integer value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value11(Timestamp value) {
        setRecordingDate(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value12(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value13(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value14(Integer value) {
        setLocationId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value15(Integer value) {
        setTreatmentId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord value16(Integer value) {
        setTrialseriesId(value);
        return this;
    }

    @Override
    public PhenotypedataRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, String value9, Integer value10, Timestamp value11, Timestamp value12, Timestamp value13, Integer value14, Integer value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhenotypedataRecord
     */
    public PhenotypedataRecord() {
        super(Phenotypedata.PHENOTYPEDATA);
    }

    /**
     * Create a detached, initialised PhenotypedataRecord
     */
    public PhenotypedataRecord(Integer id, Integer phenotypeId, Integer germinatebaseId, String rep, String block, BigDecimal latitude, BigDecimal longitude, BigDecimal elevation, String phenotypeValue, Integer datasetId, Timestamp recordingDate, Timestamp createdOn, Timestamp updatedOn, Integer locationId, Integer treatmentId, Integer trialseriesId) {
        super(Phenotypedata.PHENOTYPEDATA);

        setId(id);
        setPhenotypeId(phenotypeId);
        setGerminatebaseId(germinatebaseId);
        setRep(rep);
        setBlock(block);
        setLatitude(latitude);
        setLongitude(longitude);
        setElevation(elevation);
        setPhenotypeValue(phenotypeValue);
        setDatasetId(datasetId);
        setRecordingDate(recordingDate);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setLocationId(locationId);
        setTreatmentId(treatmentId);
        setTrialseriesId(trialseriesId);
    }

    /**
     * Create a detached, initialised PhenotypedataRecord
     */
    public PhenotypedataRecord(jhi.germinate.server.database.codegen.tables.pojos.Phenotypedata value) {
        super(Phenotypedata.PHENOTYPEDATA);

        if (value != null) {
            setId(value.getId());
            setPhenotypeId(value.getPhenotypeId());
            setGerminatebaseId(value.getGerminatebaseId());
            setRep(value.getRep());
            setBlock(value.getBlock());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setElevation(value.getElevation());
            setPhenotypeValue(value.getPhenotypeValue());
            setDatasetId(value.getDatasetId());
            setRecordingDate(value.getRecordingDate());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setLocationId(value.getLocationId());
            setTreatmentId(value.getTreatmentId());
            setTrialseriesId(value.getTrialseriesId());
        }
    }
    // @formatter:on
}
