/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.enums.ProjectcollaboratorsRole;
import jhi.germinate.server.database.codegen.tables.Projectcollaborators;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectcollaboratorsRecord extends UpdatableRecordImpl<ProjectcollaboratorsRecord> implements Record5<Integer, Integer, ProjectcollaboratorsRole, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>germinate_db.projectcollaborators.collaborator_id</code>.
     */
    public void setCollaboratorId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>germinate_db.projectcollaborators.collaborator_id</code>.
     */
    public Integer getCollaboratorId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.projectcollaborators.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.projectcollaborators.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>germinate_db.projectcollaborators.role</code>.
     */
    public void setRole(ProjectcollaboratorsRole value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.projectcollaborators.role</code>.
     */
    public ProjectcollaboratorsRole getRole() {
        return (ProjectcollaboratorsRole) get(2);
    }

    /**
     * Setter for <code>germinate_db.projectcollaborators.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.projectcollaborators.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>germinate_db.projectcollaborators.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.projectcollaborators.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, ProjectcollaboratorsRole, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, ProjectcollaboratorsRole, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Projectcollaborators.PROJECTCOLLABORATORS.COLLABORATOR_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Projectcollaborators.PROJECTCOLLABORATORS.PROJECT_ID;
    }

    @Override
    public Field<ProjectcollaboratorsRole> field3() {
        return Projectcollaborators.PROJECTCOLLABORATORS.ROLE;
    }

    @Override
    public Field<Timestamp> field4() {
        return Projectcollaborators.PROJECTCOLLABORATORS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field5() {
        return Projectcollaborators.PROJECTCOLLABORATORS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getCollaboratorId();
    }

    @Override
    public Integer component2() {
        return getProjectId();
    }

    @Override
    public ProjectcollaboratorsRole component3() {
        return getRole();
    }

    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getCollaboratorId();
    }

    @Override
    public Integer value2() {
        return getProjectId();
    }

    @Override
    public ProjectcollaboratorsRole value3() {
        return getRole();
    }

    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    @Override
    public ProjectcollaboratorsRecord value1(Integer value) {
        setCollaboratorId(value);
        return this;
    }

    @Override
    public ProjectcollaboratorsRecord value2(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public ProjectcollaboratorsRecord value3(ProjectcollaboratorsRole value) {
        setRole(value);
        return this;
    }

    @Override
    public ProjectcollaboratorsRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ProjectcollaboratorsRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ProjectcollaboratorsRecord values(Integer value1, Integer value2, ProjectcollaboratorsRole value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectcollaboratorsRecord
     */
    public ProjectcollaboratorsRecord() {
        super(Projectcollaborators.PROJECTCOLLABORATORS);
    }

    /**
     * Create a detached, initialised ProjectcollaboratorsRecord
     */
    public ProjectcollaboratorsRecord(Integer collaboratorId, Integer projectId, ProjectcollaboratorsRole role, Timestamp createdOn, Timestamp updatedOn) {
        super(Projectcollaborators.PROJECTCOLLABORATORS);

        setCollaboratorId(collaboratorId);
        setProjectId(projectId);
        setRole(role);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ProjectcollaboratorsRecord
     */
    public ProjectcollaboratorsRecord(jhi.germinate.server.database.codegen.tables.pojos.Projectcollaborators value) {
        super(Projectcollaborators.PROJECTCOLLABORATORS);

        if (value != null) {
            setCollaboratorId(value.getCollaboratorId());
            setProjectId(value.getProjectId());
            setRole(value.getRole());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
