/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.tables.Stories;
import jhi.germinate.server.database.pojo.StoryRequirements;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoriesRecord extends UpdatableRecordImpl<StoriesRecord> implements Record12<Integer, String, String, Integer, StoryRequirements, Integer, Integer, Boolean, Boolean, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.stories.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.stories.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.stories.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.stories.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_db.stories.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.stories.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_db.stories.image_id</code>.
     */
    public void setImageId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.stories.image_id</code>.
     */
    public Integer getImageId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>germinate_db.stories.requirements</code>.
     */
    public void setRequirements(StoryRequirements value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.stories.requirements</code>.
     */
    public StoryRequirements getRequirements() {
        return (StoryRequirements) get(4);
    }

    /**
     * Setter for <code>germinate_db.stories.publication_id</code>.
     */
    public void setPublicationId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_db.stories.publication_id</code>.
     */
    public Integer getPublicationId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>germinate_db.stories.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_db.stories.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>germinate_db.stories.featured</code>.
     */
    public void setFeatured(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_db.stories.featured</code>.
     */
    public Boolean getFeatured() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>germinate_db.stories.visibility</code>.
     */
    public void setVisibility(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_db.stories.visibility</code>.
     */
    public Boolean getVisibility() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>germinate_db.stories.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>germinate_db.stories.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>germinate_db.stories.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>germinate_db.stories.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>germinate_db.stories.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>germinate_db.stories.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, Integer, StoryRequirements, Integer, Integer, Boolean, Boolean, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, Integer, StoryRequirements, Integer, Integer, Boolean, Boolean, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Stories.STORIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Stories.STORIES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Stories.STORIES.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Stories.STORIES.IMAGE_ID;
    }

    @Override
    public Field<StoryRequirements> field5() {
        return Stories.STORIES.REQUIREMENTS;
    }

    @Override
    public Field<Integer> field6() {
        return Stories.STORIES.PUBLICATION_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Stories.STORIES.PROJECT_ID;
    }

    @Override
    public Field<Boolean> field8() {
        return Stories.STORIES.FEATURED;
    }

    @Override
    public Field<Boolean> field9() {
        return Stories.STORIES.VISIBILITY;
    }

    @Override
    public Field<Integer> field10() {
        return Stories.STORIES.USER_ID;
    }

    @Override
    public Field<Timestamp> field11() {
        return Stories.STORIES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field12() {
        return Stories.STORIES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getImageId();
    }

    @Override
    public StoryRequirements component5() {
        return getRequirements();
    }

    @Override
    public Integer component6() {
        return getPublicationId();
    }

    @Override
    public Integer component7() {
        return getProjectId();
    }

    @Override
    public Boolean component8() {
        return getFeatured();
    }

    @Override
    public Boolean component9() {
        return getVisibility();
    }

    @Override
    public Integer component10() {
        return getUserId();
    }

    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component12() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getImageId();
    }

    @Override
    public StoryRequirements value5() {
        return getRequirements();
    }

    @Override
    public Integer value6() {
        return getPublicationId();
    }

    @Override
    public Integer value7() {
        return getProjectId();
    }

    @Override
    public Boolean value8() {
        return getFeatured();
    }

    @Override
    public Boolean value9() {
        return getVisibility();
    }

    @Override
    public Integer value10() {
        return getUserId();
    }

    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value12() {
        return getUpdatedOn();
    }

    @Override
    public StoriesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StoriesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StoriesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public StoriesRecord value4(Integer value) {
        setImageId(value);
        return this;
    }

    @Override
    public StoriesRecord value5(StoryRequirements value) {
        setRequirements(value);
        return this;
    }

    @Override
    public StoriesRecord value6(Integer value) {
        setPublicationId(value);
        return this;
    }

    @Override
    public StoriesRecord value7(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public StoriesRecord value8(Boolean value) {
        setFeatured(value);
        return this;
    }

    @Override
    public StoriesRecord value9(Boolean value) {
        setVisibility(value);
        return this;
    }

    @Override
    public StoriesRecord value10(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public StoriesRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public StoriesRecord value12(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public StoriesRecord values(Integer value1, String value2, String value3, Integer value4, StoryRequirements value5, Integer value6, Integer value7, Boolean value8, Boolean value9, Integer value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoriesRecord
     */
    public StoriesRecord() {
        super(Stories.STORIES);
    }

    /**
     * Create a detached, initialised StoriesRecord
     */
    public StoriesRecord(Integer id, String name, String description, Integer imageId, StoryRequirements requirements, Integer publicationId, Integer projectId, Boolean featured, Boolean visibility, Integer userId, Timestamp createdOn, Timestamp updatedOn) {
        super(Stories.STORIES);

        setId(id);
        setName(name);
        setDescription(description);
        setImageId(imageId);
        setRequirements(requirements);
        setPublicationId(publicationId);
        setProjectId(projectId);
        setFeatured(featured);
        setVisibility(visibility);
        setUserId(userId);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised StoriesRecord
     */
    public StoriesRecord(jhi.germinate.server.database.codegen.tables.pojos.Stories value) {
        super(Stories.STORIES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setImageId(value.getImageId());
            setRequirements(value.getRequirements());
            setPublicationId(value.getPublicationId());
            setProjectId(value.getProjectId());
            setFeatured(value.getFeatured());
            setVisibility(value.getVisibility());
            setUserId(value.getUserId());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
