/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.tables.Synonymtypes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * Synonym type definitions.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SynonymtypesRecord extends UpdatableRecordImpl<SynonymtypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.synonymtypes.id</code>. Primary id for this
     * table. This uniquely identifies the row.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.synonymtypes.id</code>. Primary id for this
     * table. This uniquely identifies the row.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.synonymtypes.target_table</code>. The
     * target table.
     */
    public void setTargetTable(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.synonymtypes.target_table</code>. The
     * target table.
     */
    public String getTargetTable() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_db.synonymtypes.name</code>. Name of the
     * synonym type.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.synonymtypes.name</code>. Name of the
     * synonym type.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_db.synonymtypes.description</code>.
     * Description of the type.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.synonymtypes.description</code>.
     * Description of the type.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_db.synonymtypes.created_on</code>. When the
     * record was created.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.synonymtypes.created_on</code>. When the
     * record was created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>germinate_db.synonymtypes.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public void setUpdatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_db.synonymtypes.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SynonymtypesRecord
     */
    public SynonymtypesRecord() {
        super(Synonymtypes.SYNONYMTYPES);
    }

    /**
     * Create a detached, initialised SynonymtypesRecord
     */
    public SynonymtypesRecord(Integer id, String targetTable, String name, String description, Timestamp createdOn, Timestamp updatedOn) {
        super(Synonymtypes.SYNONYMTYPES);

        setId(id);
        setTargetTable(targetTable);
        setName(name);
        setDescription(description);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SynonymtypesRecord
     */
    public SynonymtypesRecord(jhi.germinate.server.database.codegen.tables.pojos.Synonymtypes value) {
        super(Synonymtypes.SYNONYMTYPES);

        if (value != null) {
            setId(value.getId());
            setTargetTable(value.getTargetTable());
            setName(value.getName());
            setDescription(value.getDescription());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
