/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.enums.UserfeedbackFeedbackType;
import jhi.germinate.server.database.codegen.enums.UserfeedbackSeverity;
import jhi.germinate.server.database.codegen.tables.Userfeedback;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserfeedbackRecord extends UpdatableRecordImpl<UserfeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.userfeedback.id</code>. Auto-incremented
     * primary key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.id</code>. Auto-incremented
     * primary key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.content</code>. Feedback
     * content.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.content</code>. Feedback
     * content.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.image</code>. Optional
     * interface screenshot.
     */
    public void setImage(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.image</code>. Optional
     * interface screenshot.
     */
    public byte[] getImage() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.page_url</code>. The URL of
     * the page the user was looking at.
     */
    public void setPageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.page_url</code>. The URL of
     * the page the user was looking at.
     */
    public String getPageUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.user_id</code>. Optional user
     * id if user was logged in.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.user_id</code>. Optional user
     * id if user was logged in.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.contact_email</code>. Contact
     * email address.
     */
    public void setContactEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.contact_email</code>. Contact
     * email address.
     */
    public String getContactEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.feedback_type</code>. The type
     * of feedback.
     */
    public void setFeedbackType(UserfeedbackFeedbackType value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.feedback_type</code>. The type
     * of feedback.
     */
    public UserfeedbackFeedbackType getFeedbackType() {
        return (UserfeedbackFeedbackType) get(6);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.severity</code>. The estimated
     * severity of the issue.
     */
    public void setSeverity(UserfeedbackSeverity value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.severity</code>. The estimated
     * severity of the issue.
     */
    public UserfeedbackSeverity getSeverity() {
        return (UserfeedbackSeverity) get(7);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.is_new</code>. Indicates
     * whether this is new feedback or has been seen before.
     */
    public void setIsNew(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.is_new</code>. Indicates
     * whether this is new feedback or has been seen before.
     */
    public Boolean getIsNew() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.created_on</code>. When this
     * database record has been created.
     */
    public void setCreatedOn(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.created_on</code>. When this
     * database record has been created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>germinate_db.userfeedback.updated_on</code>. When this
     * database record has last been updated.
     */
    public void setUpdatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>germinate_db.userfeedback.updated_on</code>. When this
     * database record has last been updated.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserfeedbackRecord
     */
    public UserfeedbackRecord() {
        super(Userfeedback.USERFEEDBACK);
    }

    /**
     * Create a detached, initialised UserfeedbackRecord
     */
    public UserfeedbackRecord(Integer id, String content, byte[] image, String pageUrl, Integer userId, String contactEmail, UserfeedbackFeedbackType feedbackType, UserfeedbackSeverity severity, Boolean isNew, Timestamp createdOn, Timestamp updatedOn) {
        super(Userfeedback.USERFEEDBACK);

        setId(id);
        setContent(content);
        setImage(image);
        setPageUrl(pageUrl);
        setUserId(userId);
        setContactEmail(contactEmail);
        setFeedbackType(feedbackType);
        setSeverity(severity);
        setIsNew(isNew);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserfeedbackRecord
     */
    public UserfeedbackRecord(jhi.germinate.server.database.codegen.tables.pojos.Userfeedback value) {
        super(Userfeedback.USERFEEDBACK);

        if (value != null) {
            setId(value.getId());
            setContent(value.getContent());
            setImage(value.getImage());
            setPageUrl(value.getPageUrl());
            setUserId(value.getUserId());
            setContactEmail(value.getContactEmail());
            setFeedbackType(value.getFeedbackType());
            setSeverity(value.getSeverity());
            setIsNew(value.getIsNew());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
