/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import jhi.germinate.server.database.codegen.tables.ViewTableInstitutionDatasets;

import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableInstitutionDatasetsRecord extends TableRecordImpl<ViewTableInstitutionDatasetsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setInstitutionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getInstitutionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_code</code>.
     * If there is a defined ISO code for the institute this should be used
     * here.
     */
    public void setInstitutionCode(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_code</code>.
     * If there is a defined ISO code for the institute this should be used
     * here.
     */
    public String getInstitutionCode() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_name</code>.
     * The institute name.
     */
    public void setInstitutionName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_name</code>.
     * The institute name.
     */
    public String getInstitutionName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_acronym</code>.
     * If there is an acronym for the institute.
     */
    public void setInstitutionAcronym(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_acronym</code>.
     * If there is an acronym for the institute.
     */
    public String getInstitutionAcronym() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.country_name</code>.
     * Country name.
     */
    public void setCountryName(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.country_name</code>.
     * Country name.
     */
    public String getCountryName() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.country_code2</code>.
     * ISO 2 Code for country.
     */
    public void setCountryCode2(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.country_code2</code>.
     * ISO 2 Code for country.
     */
    public String getCountryCode2() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.country_code3</code>.
     * ISO 3 Code for country.
     */
    public void setCountryCode3(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.country_code3</code>.
     * ISO 3 Code for country.
     */
    public String getCountryCode3() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_contact</code>.
     * The contact at the institute which should be used for correspondence.
     */
    public void setInstitutionContact(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_contact</code>.
     * The contact at the institute which should be used for correspondence.
     */
    public String getInstitutionContact() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_phone</code>.
     * The telephone number for the institute.
     */
    public void setInstitutionPhone(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_phone</code>.
     * The telephone number for the institute.
     */
    public String getInstitutionPhone() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_email</code>.
     * The email address to contact the institute.
     */
    public void setInstitutionEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_email</code>.
     * The email address to contact the institute.
     */
    public String getInstitutionEmail() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.institution_address</code>.
     * The postal address of the institute.
     */
    public void setInstitutionAddress(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.institution_address</code>.
     * The postal address of the institute.
     */
    public String getInstitutionAddress() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.all_dataset_ids</code>.
     */
    public void setAllDatasetIds(Integer[] value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.all_dataset_ids</code>.
     */
    public Integer[] getAllDatasetIds() {
        return (Integer[]) get(11);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.trials_dataset_ids</code>.
     */
    public void setTrialsDatasetIds(Integer[] value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.trials_dataset_ids</code>.
     */
    public Integer[] getTrialsDatasetIds() {
        return (Integer[]) get(12);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.genotype_dataset_ids</code>.
     */
    public void setGenotypeDatasetIds(Integer[] value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.genotype_dataset_ids</code>.
     */
    public Integer[] getGenotypeDatasetIds() {
        return (Integer[]) get(13);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.climate_dataset_ids</code>.
     */
    public void setClimateDatasetIds(Integer[] value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.climate_dataset_ids</code>.
     */
    public Integer[] getClimateDatasetIds() {
        return (Integer[]) get(14);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_institution_datasets.pedigree_dataset_ids</code>.
     */
    public void setPedigreeDatasetIds(Integer[] value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_institution_datasets.pedigree_dataset_ids</code>.
     */
    public Integer[] getPedigreeDatasetIds() {
        return (Integer[]) get(15);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableInstitutionDatasetsRecord
     */
    public ViewTableInstitutionDatasetsRecord() {
        super(ViewTableInstitutionDatasets.VIEW_TABLE_INSTITUTION_DATASETS);
    }

    /**
     * Create a detached, initialised ViewTableInstitutionDatasetsRecord
     */
    public ViewTableInstitutionDatasetsRecord(Integer institutionId, String institutionCode, String institutionName, String institutionAcronym, String countryName, String countryCode2, String countryCode3, String institutionContact, String institutionPhone, String institutionEmail, String institutionAddress, Integer[] allDatasetIds, Integer[] trialsDatasetIds, Integer[] genotypeDatasetIds, Integer[] climateDatasetIds, Integer[] pedigreeDatasetIds) {
        super(ViewTableInstitutionDatasets.VIEW_TABLE_INSTITUTION_DATASETS);

        setInstitutionId(institutionId);
        setInstitutionCode(institutionCode);
        setInstitutionName(institutionName);
        setInstitutionAcronym(institutionAcronym);
        setCountryName(countryName);
        setCountryCode2(countryCode2);
        setCountryCode3(countryCode3);
        setInstitutionContact(institutionContact);
        setInstitutionPhone(institutionPhone);
        setInstitutionEmail(institutionEmail);
        setInstitutionAddress(institutionAddress);
        setAllDatasetIds(allDatasetIds);
        setTrialsDatasetIds(trialsDatasetIds);
        setGenotypeDatasetIds(genotypeDatasetIds);
        setClimateDatasetIds(climateDatasetIds);
        setPedigreeDatasetIds(pedigreeDatasetIds);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewTableInstitutionDatasetsRecord
     */
    public ViewTableInstitutionDatasetsRecord(jhi.germinate.server.database.codegen.tables.pojos.ViewTableInstitutionDatasets value) {
        super(ViewTableInstitutionDatasets.VIEW_TABLE_INSTITUTION_DATASETS);

        if (value != null) {
            setInstitutionId(value.getInstitutionId());
            setInstitutionCode(value.getInstitutionCode());
            setInstitutionName(value.getInstitutionName());
            setInstitutionAcronym(value.getInstitutionAcronym());
            setCountryName(value.getCountryName());
            setCountryCode2(value.getCountryCode2());
            setCountryCode3(value.getCountryCode3());
            setInstitutionContact(value.getInstitutionContact());
            setInstitutionPhone(value.getInstitutionPhone());
            setInstitutionEmail(value.getInstitutionEmail());
            setInstitutionAddress(value.getInstitutionAddress());
            setAllDatasetIds(value.getAllDatasetIds());
            setTrialsDatasetIds(value.getTrialsDatasetIds());
            setGenotypeDatasetIds(value.getGenotypeDatasetIds());
            setClimateDatasetIds(value.getClimateDatasetIds());
            setPedigreeDatasetIds(value.getPedigreeDatasetIds());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
