/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import jhi.germinate.server.database.codegen.tables.ViewTableTaxonomies;
import jhi.germinate.server.database.pojo.TaxonomyProviderInfo;

import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewTableTaxonomiesRecord extends TableRecordImpl<ViewTableTaxonomiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>germinate_db.view_table_taxonomies.taxonomy_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setTaxonomyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_db.view_table_taxonomies.taxonomy_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getTaxonomyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_genus</code>. Genus
     * name for the species.
     */
    public void setTaxonomyGenus(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_genus</code>. Genus
     * name for the species.
     */
    public String getTaxonomyGenus() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_species</code>. Species
     * name in lowercase.
     */
    public void setTaxonomySpecies(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_species</code>. Species
     * name in lowercase.
     */
    public String getTaxonomySpecies() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_subtaxa</code>. Subtaxa
     * name.
     */
    public void setTaxonomySubtaxa(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_subtaxa</code>. Subtaxa
     * name.
     */
    public String getTaxonomySubtaxa() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_cropname</code>. The
     * name of the crop. This should be the common name. Examples would include
     * barley, maize, wheat, rice and so on.
     */
    public void setTaxonomyCropname(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_cropname</code>. The
     * name of the crop. This should be the common name. Examples would include
     * barley, maize, wheat, rice and so on.
     */
    public String getTaxonomyCropname() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_providers</code>.
     */
    public void setTaxonomyProviders(TaxonomyProviderInfo[] value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_taxonomies.taxonomy_providers</code>.
     */
    public TaxonomyProviderInfo[] getTaxonomyProviders() {
        return (TaxonomyProviderInfo[]) get(5);
    }

    /**
     * Setter for <code>germinate_db.view_table_taxonomies.count</code>.
     */
    public void setCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_db.view_table_taxonomies.count</code>.
     */
    public Long getCount() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableTaxonomiesRecord
     */
    public ViewTableTaxonomiesRecord() {
        super(ViewTableTaxonomies.VIEW_TABLE_TAXONOMIES);
    }

    /**
     * Create a detached, initialised ViewTableTaxonomiesRecord
     */
    public ViewTableTaxonomiesRecord(Integer taxonomyId, String taxonomyGenus, String taxonomySpecies, String taxonomySubtaxa, String taxonomyCropname, TaxonomyProviderInfo[] taxonomyProviders, Long count) {
        super(ViewTableTaxonomies.VIEW_TABLE_TAXONOMIES);

        setTaxonomyId(taxonomyId);
        setTaxonomyGenus(taxonomyGenus);
        setTaxonomySpecies(taxonomySpecies);
        setTaxonomySubtaxa(taxonomySubtaxa);
        setTaxonomyCropname(taxonomyCropname);
        setTaxonomyProviders(taxonomyProviders);
        setCount(count);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewTableTaxonomiesRecord
     */
    public ViewTableTaxonomiesRecord(jhi.germinate.server.database.codegen.tables.pojos.ViewTableTaxonomies value) {
        super(ViewTableTaxonomies.VIEW_TABLE_TAXONOMIES);

        if (value != null) {
            setTaxonomyId(value.getTaxonomyId());
            setTaxonomyGenus(value.getTaxonomyGenus());
            setTaxonomySpecies(value.getTaxonomySpecies());
            setTaxonomySubtaxa(value.getTaxonomySubtaxa());
            setTaxonomyCropname(value.getTaxonomyCropname());
            setTaxonomyProviders(value.getTaxonomyProviders());
            setCount(value.getCount());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
