/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.tables.ViewTablePedigreedefinitions;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTablePedigreedefinitionsRecord extends TableRecordImpl<ViewTablePedigreedefinitionsRecord> implements Record13<Integer, String, String, String, String, Integer, String, Integer, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setGermplasmId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getGermplasmId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_name</code>.
     * A unique name which defines an entry in the germinatbase table.
     */
    public void setGermplasmName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.germplasm_name</code>.
     * A unique name which defines an entry in the germinatbase table.
     */
    public String getGermplasmName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_name</code>.
     * Name of the reference notation source.
     */
    public void setPedigreeNotationName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_name</code>.
     * Name of the reference notation source.
     */
    public String getPedigreeNotationName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_description</code>.
     * A longer description about the reference notation source.
     */
    public void setPedigreeNotationDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_description</code>.
     * A longer description about the reference notation source.
     */
    public String getPedigreeNotationDescription() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_url</code>.
     * Hyperlink to the notation source.
     */
    public void setPedigreeNotationUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_notation_url</code>.
     * Hyperlink to the notation source.
     */
    public String getPedigreeNotationUrl() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setDatasetId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getDatasetId() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_name</code>.
     * Describes the dataset.
     */
    public void setDatasetName(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.dataset_name</code>.
     * Describes the dataset.
     */
    public String getDatasetName() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public void setDefinitionId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition_id</code>.
     * Primary id for this table. This uniquely identifies the row.
     */
    public Integer getDefinitionId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition</code>. The
     * pedigree string which is used to represent the germinatebase entry.
     */
    public void setDefinition(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.definition</code>. The
     * pedigree string which is used to represent the germinatebase entry.
     */
    public String getDefinition() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_name</code>.
     * The name of the pedigree.
     */
    public void setPedigreeDescriptionName(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_name</code>.
     * The name of the pedigree.
     */
    public String getPedigreeDescriptionName() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_description</code>.
     * Describes the pedigree in more detail.
     */
    public void setPedigreeDescriptionDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_description</code>.
     * Describes the pedigree in more detail.
     */
    public String getPedigreeDescriptionDescription() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_author</code>.
     * Who is responsible for the creation of the pedigree. Attribution should
     * be included in here for pedigree sources.
     */
    public void setPedigreeDescriptionAuthor(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.pedigree_description_author</code>.
     * Who is responsible for the creation of the pedigree. Attribution should
     * be included in here for pedigree sources.
     */
    public String getPedigreeDescriptionAuthor() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>germinate_db.view_table_pedigreedefinitions.created_on</code>. When
     * the record was created.
     */
    public void setCreatedOn(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>germinate_db.view_table_pedigreedefinitions.created_on</code>. When
     * the record was created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, String, String, Integer, String, Integer, String, String, String, String, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, String, String, String, Integer, String, Integer, String, String, String, String, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.GERMPLASM_ID;
    }

    @Override
    public Field<String> field2() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.GERMPLASM_NAME;
    }

    @Override
    public Field<String> field3() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.PEDIGREE_NOTATION_NAME;
    }

    @Override
    public Field<String> field4() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.PEDIGREE_NOTATION_DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.PEDIGREE_NOTATION_URL;
    }

    @Override
    public Field<Integer> field6() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.DATASET_ID;
    }

    @Override
    public Field<String> field7() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.DATASET_NAME;
    }

    @Override
    public Field<Integer> field8() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.DEFINITION_ID;
    }

    @Override
    public Field<String> field9() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.DEFINITION;
    }

    @Override
    public Field<String> field10() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.PEDIGREE_DESCRIPTION_NAME;
    }

    @Override
    public Field<String> field11() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.PEDIGREE_DESCRIPTION_DESCRIPTION;
    }

    @Override
    public Field<String> field12() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.PEDIGREE_DESCRIPTION_AUTHOR;
    }

    @Override
    public Field<Timestamp> field13() {
        return ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS.CREATED_ON;
    }

    @Override
    public Integer component1() {
        return getGermplasmId();
    }

    @Override
    public String component2() {
        return getGermplasmName();
    }

    @Override
    public String component3() {
        return getPedigreeNotationName();
    }

    @Override
    public String component4() {
        return getPedigreeNotationDescription();
    }

    @Override
    public String component5() {
        return getPedigreeNotationUrl();
    }

    @Override
    public Integer component6() {
        return getDatasetId();
    }

    @Override
    public String component7() {
        return getDatasetName();
    }

    @Override
    public Integer component8() {
        return getDefinitionId();
    }

    @Override
    public String component9() {
        return getDefinition();
    }

    @Override
    public String component10() {
        return getPedigreeDescriptionName();
    }

    @Override
    public String component11() {
        return getPedigreeDescriptionDescription();
    }

    @Override
    public String component12() {
        return getPedigreeDescriptionAuthor();
    }

    @Override
    public Timestamp component13() {
        return getCreatedOn();
    }

    @Override
    public Integer value1() {
        return getGermplasmId();
    }

    @Override
    public String value2() {
        return getGermplasmName();
    }

    @Override
    public String value3() {
        return getPedigreeNotationName();
    }

    @Override
    public String value4() {
        return getPedigreeNotationDescription();
    }

    @Override
    public String value5() {
        return getPedigreeNotationUrl();
    }

    @Override
    public Integer value6() {
        return getDatasetId();
    }

    @Override
    public String value7() {
        return getDatasetName();
    }

    @Override
    public Integer value8() {
        return getDefinitionId();
    }

    @Override
    public String value9() {
        return getDefinition();
    }

    @Override
    public String value10() {
        return getPedigreeDescriptionName();
    }

    @Override
    public String value11() {
        return getPedigreeDescriptionDescription();
    }

    @Override
    public String value12() {
        return getPedigreeDescriptionAuthor();
    }

    @Override
    public Timestamp value13() {
        return getCreatedOn();
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value1(Integer value) {
        setGermplasmId(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value2(String value) {
        setGermplasmName(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value3(String value) {
        setPedigreeNotationName(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value4(String value) {
        setPedigreeNotationDescription(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value5(String value) {
        setPedigreeNotationUrl(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value6(Integer value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value7(String value) {
        setDatasetName(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value8(Integer value) {
        setDefinitionId(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value9(String value) {
        setDefinition(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value10(String value) {
        setPedigreeDescriptionName(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value11(String value) {
        setPedigreeDescriptionDescription(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value12(String value) {
        setPedigreeDescriptionAuthor(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord value13(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ViewTablePedigreedefinitionsRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, Integer value8, String value9, String value10, String value11, String value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTablePedigreedefinitionsRecord
     */
    public ViewTablePedigreedefinitionsRecord() {
        super(ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS);
    }

    /**
     * Create a detached, initialised ViewTablePedigreedefinitionsRecord
     */
    public ViewTablePedigreedefinitionsRecord(Integer germplasmId, String germplasmName, String pedigreeNotationName, String pedigreeNotationDescription, String pedigreeNotationUrl, Integer datasetId, String datasetName, Integer definitionId, String definition, String pedigreeDescriptionName, String pedigreeDescriptionDescription, String pedigreeDescriptionAuthor, Timestamp createdOn) {
        super(ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS);

        setGermplasmId(germplasmId);
        setGermplasmName(germplasmName);
        setPedigreeNotationName(pedigreeNotationName);
        setPedigreeNotationDescription(pedigreeNotationDescription);
        setPedigreeNotationUrl(pedigreeNotationUrl);
        setDatasetId(datasetId);
        setDatasetName(datasetName);
        setDefinitionId(definitionId);
        setDefinition(definition);
        setPedigreeDescriptionName(pedigreeDescriptionName);
        setPedigreeDescriptionDescription(pedigreeDescriptionDescription);
        setPedigreeDescriptionAuthor(pedigreeDescriptionAuthor);
        setCreatedOn(createdOn);
    }

    /**
     * Create a detached, initialised ViewTablePedigreedefinitionsRecord
     */
    public ViewTablePedigreedefinitionsRecord(jhi.germinate.server.database.codegen.tables.pojos.ViewTablePedigreedefinitions value) {
        super(ViewTablePedigreedefinitions.VIEW_TABLE_PEDIGREEDEFINITIONS);

        if (value != null) {
            setGermplasmId(value.getGermplasmId());
            setGermplasmName(value.getGermplasmName());
            setPedigreeNotationName(value.getPedigreeNotationName());
            setPedigreeNotationDescription(value.getPedigreeNotationDescription());
            setPedigreeNotationUrl(value.getPedigreeNotationUrl());
            setDatasetId(value.getDatasetId());
            setDatasetName(value.getDatasetName());
            setDefinitionId(value.getDefinitionId());
            setDefinition(value.getDefinition());
            setPedigreeDescriptionName(value.getPedigreeDescriptionName());
            setPedigreeDescriptionDescription(value.getPedigreeDescriptionDescription());
            setPedigreeDescriptionAuthor(value.getPedigreeDescriptionAuthor());
            setCreatedOn(value.getCreatedOn());
        }
    }
    // @formatter:on
}
