/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.GerminateDb;
import jhi.germinate.server.database.codegen.tables.records.ClimateoverlaysRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * Climate overlays can be used in conjunction with OpenStreetMap in order to
 * visualize climate data in a geographic context.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Climateoverlays extends TableImpl<ClimateoverlaysRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>germinate_db.climateoverlays</code>
     */
    public static final Climateoverlays CLIMATEOVERLAYS = new Climateoverlays();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClimateoverlaysRecord> getRecordType() {
        return ClimateoverlaysRecord.class;
    }

    /**
     * The column <code>germinate_db.climateoverlays.id</code>. Primary id for
     * this table. This uniquely identifies the row.
     */
    public final TableField<ClimateoverlaysRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary id for this table. This uniquely identifies the row.");

    /**
     * The column <code>germinate_db.climateoverlays.climate_id</code>. Foreign
     * key to climates (climates.id).
     */
    public final TableField<ClimateoverlaysRecord, Integer> CLIMATE_ID = createField(DSL.name("climate_id"), SQLDataType.INTEGER.nullable(false), this, "Foreign key to climates (climates.id).");

    /**
     * The column <code>germinate_db.climateoverlays.path</code>. This is the
     * path for holding images which can be used as overlays for the Google Maps
     * representation in Germinate. The path is relative.
     */
    public final TableField<ClimateoverlaysRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(255).nullable(false), this, "This is the path for holding images which can be used as overlays for the Google Maps representation in Germinate. The path is relative.");

    /**
     * The column
     * <code>germinate_db.climateoverlays.bottom_left_longitude</code>. Allows
     * the allignment of images against OpenStreetMap API.
     */
    public final TableField<ClimateoverlaysRecord, Double> BOTTOM_LEFT_LONGITUDE = createField(DSL.name("bottom_left_longitude"), SQLDataType.DOUBLE, this, "Allows the allignment of images against OpenStreetMap API.");

    /**
     * The column
     * <code>germinate_db.climateoverlays.bottom_left_latitude</code>. Allows
     * the allignment of images against OpenStreetMap API.
     */
    public final TableField<ClimateoverlaysRecord, Double> BOTTOM_LEFT_LATITUDE = createField(DSL.name("bottom_left_latitude"), SQLDataType.DOUBLE, this, "Allows the allignment of images against OpenStreetMap API.");

    /**
     * The column <code>germinate_db.climateoverlays.top_right_longitude</code>.
     * Allows the allignment of images against OpenStreetMap API.
     */
    public final TableField<ClimateoverlaysRecord, Double> TOP_RIGHT_LONGITUDE = createField(DSL.name("top_right_longitude"), SQLDataType.DOUBLE, this, "Allows the allignment of images against OpenStreetMap API.");

    /**
     * The column <code>germinate_db.climateoverlays.top_right_latitude</code>.
     * Allows the allignment of images against OpenStreetMap API.
     */
    public final TableField<ClimateoverlaysRecord, Double> TOP_RIGHT_LATITUDE = createField(DSL.name("top_right_latitude"), SQLDataType.DOUBLE, this, "Allows the allignment of images against OpenStreetMap API.");

    /**
     * The column <code>germinate_db.climateoverlays.is_legend</code>. The
     * legend for the image. What colours represent in the overlays. This is not
     * required but used if present. 
     */
    public final TableField<ClimateoverlaysRecord, Boolean> IS_LEGEND = createField(DSL.name("is_legend"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "The legend for the image. What colours represent in the overlays. This is not required but used if present. ");

    /**
     * The column <code>germinate_db.climateoverlays.description</code>.
     * Describes the climate overlay if additional explanation of  the overlay
     * image is required.
     */
    public final TableField<ClimateoverlaysRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "Describes the climate overlay if additional explanation of  the overlay image is required.");

    /**
     * The column <code>germinate_db.climateoverlays.created_on</code>. When the
     * record was created.
     */
    public final TableField<ClimateoverlaysRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "When the record was created.");

    /**
     * The column <code>germinate_db.climateoverlays.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public final TableField<ClimateoverlaysRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.");

    private Climateoverlays(Name alias, Table<ClimateoverlaysRecord> aliased) {
        this(alias, aliased, null);
    }

    private Climateoverlays(Name alias, Table<ClimateoverlaysRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Climate overlays can be used in conjunction with OpenStreetMap in order to visualize climate data in a geographic context."), TableOptions.table());
    }

    /**
     * Create an aliased <code>germinate_db.climateoverlays</code> table
     * reference
     */
    public Climateoverlays(String alias) {
        this(DSL.name(alias), CLIMATEOVERLAYS);
    }

    /**
     * Create an aliased <code>germinate_db.climateoverlays</code> table
     * reference
     */
    public Climateoverlays(Name alias) {
        this(alias, CLIMATEOVERLAYS);
    }

    /**
     * Create a <code>germinate_db.climateoverlays</code> table reference
     */
    public Climateoverlays() {
        this(DSL.name("climateoverlays"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : GerminateDb.GERMINATE_DB;
    }

    @Override
    public Identity<ClimateoverlaysRecord, Integer> getIdentity() {
        return (Identity<ClimateoverlaysRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClimateoverlaysRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Climateoverlays.CLIMATEOVERLAYS, DSL.name("KEY_climateoverlays_PRIMARY"), new TableField[] { Climateoverlays.CLIMATEOVERLAYS.ID }, true);
    }

    @Override
    public Climateoverlays as(String alias) {
        return new Climateoverlays(DSL.name(alias), this);
    }

    @Override
    public Climateoverlays as(Name alias) {
        return new Climateoverlays(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Climateoverlays rename(String name) {
        return new Climateoverlays(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Climateoverlays rename(Name name) {
        return new Climateoverlays(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, String, Double, Double, Double, Double, Boolean, String, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
    // @formatter:on
}
