/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables;


import java.sql.Date;
import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.GerminateDb;
import jhi.germinate.server.database.codegen.tables.records.GerminatebaseRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * Germinatebase is the Germinate base table which contains passport and other
 * germplasm definition data.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Germinatebase extends TableImpl<GerminatebaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>germinate_db.germinatebase</code>
     */
    public static final Germinatebase GERMINATEBASE = new Germinatebase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GerminatebaseRecord> getRecordType() {
        return GerminatebaseRecord.class;
    }

    /**
     * The column <code>germinate_db.germinatebase.id</code>. Primary id for
     * this table. This uniquely identifies the row.
     */
    public final TableField<GerminatebaseRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary id for this table. This uniquely identifies the row.");

    /**
     * The column <code>germinate_db.germinatebase.general_identifier</code>. A
     * unique identifier.
     */
    public final TableField<GerminatebaseRecord, String> GENERAL_IDENTIFIER = createField(DSL.name("general_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "A unique identifier.");

    /**
     * The column <code>germinate_db.germinatebase.number</code>. This is the
     * unique identifier for accessions within a genebank, and is assigned when
     * a sample is
     * entered into the genebank collection (e.g. ‘PI 113869’).
     */
    public final TableField<GerminatebaseRecord, String> NUMBER = createField(DSL.name("number"), SQLDataType.VARCHAR(255), this, "This is the unique identifier for accessions within a genebank, and is assigned when a sample is\nentered into the genebank collection (e.g. ‘PI 113869’).");

    /**
     * The column <code>germinate_db.germinatebase.name</code>. A unique name
     * which defines an entry in the germinatbase table.
     */
    public final TableField<GerminatebaseRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "A unique name which defines an entry in the germinatbase table.");

    /**
     * The column <code>germinate_db.germinatebase.bank_number</code>.
     * Alternative genebank number.
     */
    public final TableField<GerminatebaseRecord, String> BANK_NUMBER = createField(DSL.name("bank_number"), SQLDataType.VARCHAR(255), this, "Alternative genebank number.");

    /**
     * The column <code>germinate_db.germinatebase.breeders_code</code>. FAO
     * WIEWS code of the institute that has bred the material. If the holding
     * institute has bred the material, the breeding institute code (BREDCODE)
     * should be the same as the holding institute code (INSTCODE). Follows
     * INSTCODE standard. Multiple values are separated by a semicolon without
     * space.
     */
    public final TableField<GerminatebaseRecord, String> BREEDERS_CODE = createField(DSL.name("breeders_code"), SQLDataType.CHAR(50), this, "FAO WIEWS code of the institute that has bred the material. If the holding institute has bred the material, the breeding institute code (BREDCODE) should be the same as the holding institute code (INSTCODE). Follows INSTCODE standard. Multiple values are separated by a semicolon without space.");

    /**
     * The column <code>germinate_db.germinatebase.breeders_name</code>. Name of
     * the institute (or person) that bred the material. This descriptor should
     * be used only if BREDCODE cannot be filled because the FAO WIEWS code for
     * this institute is not available. Multiple names are separated by a
     * semicolon without space.
     */
    public final TableField<GerminatebaseRecord, String> BREEDERS_NAME = createField(DSL.name("breeders_name"), SQLDataType.VARCHAR(255), this, "Name of the institute (or person) that bred the material. This descriptor should be used only if BREDCODE cannot be filled because the FAO WIEWS code for this institute is not available. Multiple names are separated by a semicolon without space.");

    /**
     * The column <code>germinate_db.germinatebase.taxonomy_id</code>. Foreign
     * key to taxonomies (taxonomies.id).
     */
    public final TableField<GerminatebaseRecord, Integer> TAXONOMY_ID = createField(DSL.name("taxonomy_id"), SQLDataType.INTEGER, this, "Foreign key to taxonomies (taxonomies.id).");

    /**
     * The column <code>germinate_db.germinatebase.institution_id</code>.
     * Foreign key to institutions (institutions.id).
     */
    public final TableField<GerminatebaseRecord, Integer> INSTITUTION_ID = createField(DSL.name("institution_id"), SQLDataType.INTEGER, this, "Foreign key to institutions (institutions.id).");

    /**
     * The column <code>germinate_db.germinatebase.plant_passport</code>. Record
     * if the entry has a plant passport.
     */
    public final TableField<GerminatebaseRecord, String> PLANT_PASSPORT = createField(DSL.name("plant_passport"), SQLDataType.VARCHAR(255), this, "Record if the entry has a plant passport.");

    /**
     * The column <code>germinate_db.germinatebase.donor_code</code>. FAO WIEWS
     * code of the donor institute. Follows INSTCODE standard.
     */
    public final TableField<GerminatebaseRecord, String> DONOR_CODE = createField(DSL.name("donor_code"), SQLDataType.VARCHAR(255), this, "FAO WIEWS code of the donor institute. Follows INSTCODE standard.");

    /**
     * The column <code>germinate_db.germinatebase.donor_name</code>. Name of
     * the donor institute (or person). This descriptor should be used only if
     * DONORCODE cannot be filled because the FAO WIEWS code for this institute
     * is not available.
     */
    public final TableField<GerminatebaseRecord, String> DONOR_NAME = createField(DSL.name("donor_name"), SQLDataType.VARCHAR(255), this, "Name of the donor institute (or person). This descriptor should be used only if DONORCODE cannot be filled because the FAO WIEWS code for this institute is not available.");

    /**
     * The column <code>germinate_db.germinatebase.donor_number</code>.
     * Identifier assigned to an accession by the donor. Follows ACCENUMB
     * standard.
     */
    public final TableField<GerminatebaseRecord, String> DONOR_NUMBER = createField(DSL.name("donor_number"), SQLDataType.VARCHAR(255), this, "Identifier assigned to an accession by the donor. Follows ACCENUMB standard.");

    /**
     * The column <code>germinate_db.germinatebase.acqdate</code>. Date on which
     * the accession entered the collection where YYYY is the year, MM is the
     * month and
     * DD is the day. Missing data (MM or DD) should be indicated with hyphens
     * or ‘00’ [double zero].
     */
    public final TableField<GerminatebaseRecord, String> ACQDATE = createField(DSL.name("acqdate"), SQLDataType.VARCHAR(255), this, "Date on which the accession entered the collection where YYYY is the year, MM is the month and\nDD is the day. Missing data (MM or DD) should be indicated with hyphens or ‘00’ [double zero].");

    /**
     * The column <code>germinate_db.germinatebase.collnumb</code>. Original
     * identifier assigned by the collector(s) of the sample, normally composed
     * of the name or
     * initials of the collector(s) followed by a number (e.g. ‘FM9909’). This
     * identifier is essential for
     * identifying duplicates held in different collections.
     */
    public final TableField<GerminatebaseRecord, String> COLLNUMB = createField(DSL.name("collnumb"), SQLDataType.VARCHAR(255), this, "Original identifier assigned by the collector(s) of the sample, normally composed of the name or\ninitials of the collector(s) followed by a number (e.g. ‘FM9909’). This identifier is essential for\nidentifying duplicates held in different collections.");

    /**
     * The column <code>germinate_db.germinatebase.colldate</code>. Collecting
     * date of the sample, where YYYY is the year, MM is the month and DD is the
     * day.
     * Missing data (MM or DD) should be indicated with hyphens or ‘00’ [double
     * zero]. 
     */
    public final TableField<GerminatebaseRecord, Date> COLLDATE = createField(DSL.name("colldate"), SQLDataType.DATE, this, "Collecting date of the sample, where YYYY is the year, MM is the month and DD is the day.\nMissing data (MM or DD) should be indicated with hyphens or ‘00’ [double zero]. ");

    /**
     * The column <code>germinate_db.germinatebase.collcode</code>. FAO WIEWS
     * code of the institute collecting the sample. If the holding institute has
     * collected the
     * material, the collecting institute code (COLLCODE) should be the same as
     * the holding institute
     * code (INSTCODE). Follows INSTCODE standard. Multiple values are separated
     * by a semicolon
     * without space.
     */
    public final TableField<GerminatebaseRecord, String> COLLCODE = createField(DSL.name("collcode"), SQLDataType.VARCHAR(255), this, "FAO WIEWS code of the institute collecting the sample. If the holding institute has collected the\nmaterial, the collecting institute code (COLLCODE) should be the same as the holding institute\ncode (INSTCODE). Follows INSTCODE standard. Multiple values are separated by a semicolon\nwithout space.");

    /**
     * The column <code>germinate_db.germinatebase.collname</code>. Name of the
     * institute collecting the sample. This descriptor should be used only if
     * COLLCODE cannot be filled because the FAO WIEWS code for this institute
     * is not available. Multiple values are separated by a semicolon without
     * space.
     */
    public final TableField<GerminatebaseRecord, String> COLLNAME = createField(DSL.name("collname"), SQLDataType.VARCHAR(255), this, "Name of the institute collecting the sample. This descriptor should be used only if COLLCODE cannot be filled because the FAO WIEWS code for this institute is not available. Multiple values are separated by a semicolon without space.");

    /**
     * The column <code>germinate_db.germinatebase.collmissid</code>. Identifier
     * of the collecting mission used by the Collecting Institute (4 or 4.1)
     * (e.g. 'CIATFOR-052', 'CN426').
     */
    public final TableField<GerminatebaseRecord, String> COLLMISSID = createField(DSL.name("collmissid"), SQLDataType.VARCHAR(255), this, "Identifier of the collecting mission used by the Collecting Institute (4 or 4.1) (e.g. 'CIATFOR-052', 'CN426').");

    /**
     * The column <code>germinate_db.germinatebase.othernumb</code>. Any other
     * identifiers known to exist in other collections for this accession. Use
     * the following format: INSTCODE:ACCENUMB;INSTCODE:identifier;… INSTCODE
     * and identifier are separated by a colon without space. Pairs of INSTCODE
     * and identifier are separated by a semicolon without space. When the
     * institute is not known, the identifier should be preceded by a colon.
     */
    public final TableField<GerminatebaseRecord, String> OTHERNUMB = createField(DSL.name("othernumb"), SQLDataType.CLOB, this, "Any other identifiers known to exist in other collections for this accession. Use the following format: INSTCODE:ACCENUMB;INSTCODE:identifier;… INSTCODE and identifier are separated by a colon without space. Pairs of INSTCODE and identifier are separated by a semicolon without space. When the institute is not known, the identifier should be preceded by a colon.");

    /**
     * The column <code>germinate_db.germinatebase.duplsite</code>. FAO WIEWS
     * code of the institute(s) where a safety duplicate of the accession is
     * maintained.
     * Multiple values are separated by a semicolon without space. Follows
     * INSTCODE standard.
     */
    public final TableField<GerminatebaseRecord, String> DUPLSITE = createField(DSL.name("duplsite"), SQLDataType.VARCHAR(255), this, "FAO WIEWS code of the institute(s) where a safety duplicate of the accession is maintained.\nMultiple values are separated by a semicolon without space. Follows INSTCODE standard.");

    /**
     * The column <code>germinate_db.germinatebase.duplinstname</code>. Name of
     * the institute where a safety duplicate of the accession is maintained.
     * Multiple values are separated by a semicolon without space.
     */
    public final TableField<GerminatebaseRecord, String> DUPLINSTNAME = createField(DSL.name("duplinstname"), SQLDataType.VARCHAR(255), this, "Name of the institute where a safety duplicate of the accession is maintained. Multiple values are separated by a semicolon without space.");

    /**
     * The column <code>germinate_db.germinatebase.mlsstatus_id</code>. Foreign
     * key to mlsstatus (mlsstatus.id).
     */
    public final TableField<GerminatebaseRecord, Integer> MLSSTATUS_ID = createField(DSL.name("mlsstatus_id"), SQLDataType.INTEGER, this, "Foreign key to mlsstatus (mlsstatus.id).");

    /**
     * The column <code>germinate_db.germinatebase.puid</code>. Any persistent,
     * unique identifier assigned to the accession so it can be unambiguously
     * referenced at the global level and the information associated with it
     * harvested through automated means. Report one PUID for each accession.
     */
    public final TableField<GerminatebaseRecord, String> PUID = createField(DSL.name("puid"), SQLDataType.VARCHAR(255), this, "Any persistent, unique identifier assigned to the accession so it can be unambiguously referenced at the global level and the information associated with it harvested through automated means. Report one PUID for each accession.");

    /**
     * The column <code>germinate_db.germinatebase.biologicalstatus_id</code>.
     * Foreign key to biologicalstatus (biologicalstaus.id).
     */
    public final TableField<GerminatebaseRecord, Integer> BIOLOGICALSTATUS_ID = createField(DSL.name("biologicalstatus_id"), SQLDataType.INTEGER, this, "Foreign key to biologicalstatus (biologicalstaus.id).");

    /**
     * The column <code>germinate_db.germinatebase.collsrc_id</code>. Foreign
     * key to collectionsources (collectionsources.id).
     */
    public final TableField<GerminatebaseRecord, Integer> COLLSRC_ID = createField(DSL.name("collsrc_id"), SQLDataType.INTEGER, this, "Foreign key to collectionsources (collectionsources.id).");

    /**
     * The column <code>germinate_db.germinatebase.location_id</code>. Foreign
     * key to locations (locations.id).
     */
    public final TableField<GerminatebaseRecord, Integer> LOCATION_ID = createField(DSL.name("location_id"), SQLDataType.INTEGER, this, "Foreign key to locations (locations.id).");

    /**
     * The column <code>germinate_db.germinatebase.entitytype_id</code>. Foreign
     * key to entitytypes (entitytypes.id).
     */
    public final TableField<GerminatebaseRecord, Integer> ENTITYTYPE_ID = createField(DSL.name("entitytype_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "Foreign key to entitytypes (entitytypes.id).");

    /**
     * The column <code>germinate_db.germinatebase.entityparent_id</code>.
     * Foreign key to germinatebase (germinatebase.id).
     */
    public final TableField<GerminatebaseRecord, Integer> ENTITYPARENT_ID = createField(DSL.name("entityparent_id"), SQLDataType.INTEGER, this, "Foreign key to germinatebase (germinatebase.id).");

    /**
     * The column <code>germinate_db.germinatebase.pdci</code>. Passport Data
     * Completeness Index. This is calculated by Germinate. Manual editing of
     * this field will be overwritten.
     */
    public final TableField<GerminatebaseRecord, Double> PDCI = createField(DSL.name("pdci"), SQLDataType.FLOAT, this, "Passport Data Completeness Index. This is calculated by Germinate. Manual editing of this field will be overwritten.");

    /**
     * The column <code>germinate_db.germinatebase.created_on</code>. When the
     * record was created.
     */
    public final TableField<GerminatebaseRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "When the record was created.");

    /**
     * The column <code>germinate_db.germinatebase.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public final TableField<GerminatebaseRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.");

    private Germinatebase(Name alias, Table<GerminatebaseRecord> aliased) {
        this(alias, aliased, null);
    }

    private Germinatebase(Name alias, Table<GerminatebaseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Germinatebase is the Germinate base table which contains passport and other germplasm definition data."), TableOptions.table());
    }

    /**
     * Create an aliased <code>germinate_db.germinatebase</code> table reference
     */
    public Germinatebase(String alias) {
        this(DSL.name(alias), GERMINATEBASE);
    }

    /**
     * Create an aliased <code>germinate_db.germinatebase</code> table reference
     */
    public Germinatebase(Name alias) {
        this(alias, GERMINATEBASE);
    }

    /**
     * Create a <code>germinate_db.germinatebase</code> table reference
     */
    public Germinatebase() {
        this(DSL.name("germinatebase"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : GerminateDb.GERMINATE_DB;
    }

    @Override
    public Identity<GerminatebaseRecord, Integer> getIdentity() {
        return (Identity<GerminatebaseRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GerminatebaseRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Germinatebase.GERMINATEBASE, DSL.name("KEY_germinatebase_PRIMARY"), new TableField[] { Germinatebase.GERMINATEBASE.ID }, true);
    }

    @Override
    public Germinatebase as(String alias) {
        return new Germinatebase(DSL.name(alias), this);
    }

    @Override
    public Germinatebase as(Name alias) {
        return new Germinatebase(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Germinatebase rename(String name) {
        return new Germinatebase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Germinatebase rename(Name name) {
        return new Germinatebase(name, null);
    }
    // @formatter:on
}
