/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.GerminateDb;
import jhi.germinate.server.database.codegen.tables.records.LicenselogsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Licenselogs extends TableImpl<LicenselogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>germinate_db.licenselogs</code>
     */
    public static final Licenselogs LICENSELOGS = new Licenselogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LicenselogsRecord> getRecordType() {
        return LicenselogsRecord.class;
    }

    /**
     * The column <code>germinate_db.licenselogs.id</code>.
     */
    public final TableField<LicenselogsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>germinate_db.licenselogs.license_id</code>.
     */
    public final TableField<LicenselogsRecord, Integer> LICENSE_ID = createField(DSL.name("license_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>germinate_db.licenselogs.user_id</code>.
     */
    public final TableField<LicenselogsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>germinate_db.licenselogs.accepted_on</code>.
     */
    public final TableField<LicenselogsRecord, Timestamp> ACCEPTED_ON = createField(DSL.name("accepted_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private Licenselogs(Name alias, Table<LicenselogsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Licenselogs(Name alias, Table<LicenselogsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>germinate_db.licenselogs</code> table reference
     */
    public Licenselogs(String alias) {
        this(DSL.name(alias), LICENSELOGS);
    }

    /**
     * Create an aliased <code>germinate_db.licenselogs</code> table reference
     */
    public Licenselogs(Name alias) {
        this(alias, LICENSELOGS);
    }

    /**
     * Create a <code>germinate_db.licenselogs</code> table reference
     */
    public Licenselogs() {
        this(DSL.name("licenselogs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : GerminateDb.GERMINATE_DB;
    }

    @Override
    public Identity<LicenselogsRecord, Integer> getIdentity() {
        return (Identity<LicenselogsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LicenselogsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Licenselogs.LICENSELOGS, DSL.name("KEY_licenselogs_PRIMARY"), new TableField[] { Licenselogs.LICENSELOGS.ID }, true);
    }

    @Override
    public Licenselogs as(String alias) {
        return new Licenselogs(DSL.name(alias), this);
    }

    @Override
    public Licenselogs as(Name alias) {
        return new Licenselogs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Licenselogs rename(String name) {
        return new Licenselogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Licenselogs rename(Name name) {
        return new Licenselogs(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
    // @formatter:on
}
