/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.codegen.tables;


import java.sql.Timestamp;

import jhi.germinate.server.database.codegen.GerminateDb;
import jhi.germinate.server.database.codegen.tables.records.LocationtypesRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * Describes a location.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Locationtypes extends TableImpl<LocationtypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>germinate_db.locationtypes</code>
     */
    public static final Locationtypes LOCATIONTYPES = new Locationtypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LocationtypesRecord> getRecordType() {
        return LocationtypesRecord.class;
    }

    /**
     * The column <code>germinate_db.locationtypes.id</code>. Primary id for
     * this table. This uniquely identifies the row.
     */
    public final TableField<LocationtypesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary id for this table. This uniquely identifies the row.");

    /**
     * The column <code>germinate_db.locationtypes.name</code>. The name of the
     * location type. 
     */
    public final TableField<LocationtypesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "The name of the location type. ");

    /**
     * The column <code>germinate_db.locationtypes.description</code>. A
     * description of the location type.
     */
    public final TableField<LocationtypesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "A description of the location type.");

    /**
     * The column <code>germinate_db.locationtypes.created_on</code>. When the
     * record was created.
     */
    public final TableField<LocationtypesRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "When the record was created.");

    /**
     * The column <code>germinate_db.locationtypes.updated_on</code>. When the
     * record was updated. This may be different from the created on date if
     * subsequent changes have been made to the underlying record.
     */
    public final TableField<LocationtypesRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.");

    private Locationtypes(Name alias, Table<LocationtypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Locationtypes(Name alias, Table<LocationtypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Describes a location."), TableOptions.table());
    }

    /**
     * Create an aliased <code>germinate_db.locationtypes</code> table reference
     */
    public Locationtypes(String alias) {
        this(DSL.name(alias), LOCATIONTYPES);
    }

    /**
     * Create an aliased <code>germinate_db.locationtypes</code> table reference
     */
    public Locationtypes(Name alias) {
        this(alias, LOCATIONTYPES);
    }

    /**
     * Create a <code>germinate_db.locationtypes</code> table reference
     */
    public Locationtypes() {
        this(DSL.name("locationtypes"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : GerminateDb.GERMINATE_DB;
    }

    @Override
    public Identity<LocationtypesRecord, Integer> getIdentity() {
        return (Identity<LocationtypesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LocationtypesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Locationtypes.LOCATIONTYPES, DSL.name("KEY_locationtypes_PRIMARY"), new TableField[] { Locationtypes.LOCATIONTYPES.ID }, true);
    }

    @Override
    public Locationtypes as(String alias) {
        return new Locationtypes(DSL.name(alias), this);
    }

    @Override
    public Locationtypes as(Name alias) {
        return new Locationtypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Locationtypes rename(String name) {
        return new Locationtypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Locationtypes rename(Name name) {
        return new Locationtypes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
    // @formatter:on
}
